import { parseMarkdown, type MarkdownBlock } from "./markdown";
import type { DocumentTemplate } from "./types";

export type WordDocumentPlan = {
  title: string;
  subtitle?: string;
  documentType?: WordDocumentType;
  sections: WordSection[];
};

export type WordDocumentType =
  | "lesson_plan"
  | "course_plan"
  | "report"
  | "proposal"
  | "business_plan"
  | "work_summary"
  | "research_summary"
  | "contract"
  | "notice"
  | "meeting_minutes"
  | "training_plan"
  | "summary"
  | "general";

export type WordGenerationIntent = {
  documentType: WordDocumentType;
  topic: string;
  purpose?: string;
  audience?: string;
  scope?: string;
  chapter?: string;
  chapterTitle?: string;
  duration?: string;
  lengthRequirement?: string;
  styleRequirement?: string;
  mustInclude: string[];
  requirements: string[];
  keywords: string[];
};

export type WordSection = {
  heading: string;
  level: 1 | 2 | 3 | 4;
  intro?: string;
  blocks: WordBlock[];
};

export type WordBlock =
  | { type: "paragraph"; text: string }
  | { type: "bullet_list"; items: string[] }
  | { type: "numbered_list"; items: string[] }
  | { type: "table"; headers: string[]; rows: string[][] }
  | { type: "callout"; title?: string; text: string }
  | { type: "checklist"; items: string[] }
  | { type: "rubric"; headers: string[]; rows: string[][] }
  | { type: "timeline"; headers: string[]; rows: string[][] }
  | { type: "responsibility_matrix"; headers: string[]; rows: string[][] };

const WORD_PLAN_JSON_MARKER = "WORD_DOCUMENT_PLAN_JSON";

function cleanText(value: unknown, maxLength = 360) {
  return String(value || "")
    .replace(/\s+/g, " ")
    .replace(/(?:Generated by NexusAI|由\s*NexusAI\s*生成|NexusAI\s*智能文档模块|NexusAI)/gi, "")
    .trim()
    .slice(0, maxLength);
}

function normalizeText(value: unknown) {
  return String(value || "").toLowerCase().replace(/\s+/g, "");
}

function stripHeadingNumber(value: string) {
  return cleanText(value.replace(/^(?:[一二三四五六七八九十]+、|\d+[.)、]\s*)/, ""), 120);
}

function textFromBlocks(blocks: MarkdownBlock[]) {
  return cleanText(
    blocks
      .flatMap((block) => {
        if (block.type === "heading" || block.type === "paragraph" || block.type === "code") return [block.text];
        if (block.type === "list") return block.items;
        if (block.type === "table") return block.rows.flat();
        return [];
      })
      .join(" "),
    1200
  );
}

function extractJsonObject(value: string) {
  const cleaned = String(value || "")
    .trim()
    .replace(/^```json\s*/i, "")
    .replace(/^```\s*/i, "")
    .replace(/\s*```$/i, "")
    .trim();
  const marked = cleaned.includes(WORD_PLAN_JSON_MARKER) ? cleaned.slice(cleaned.indexOf(WORD_PLAN_JSON_MARKER) + WORD_PLAN_JSON_MARKER.length) : cleaned;
  const start = marked.indexOf("{");
  const end = marked.lastIndexOf("}");
  if (start < 0 || end <= start) return null;
  return marked.slice(start, end + 1);
}

function normalizeWordBlock(value: unknown): WordBlock | null {
  const block = value as Partial<WordBlock> | null;
  if (!block || typeof block !== "object") return null;
  if (block.type === "paragraph" && typeof block.text === "string" && cleanText(block.text, 20_000)) {
    return { type: "paragraph", text: cleanText(block.text, 1200) };
  }
  if ((block.type === "bullet_list" || block.type === "numbered_list") && Array.isArray(block.items)) {
    const items = block.items.map((item) => cleanText(item, 420)).filter(Boolean);
    if (!items.length) return null;
    return { type: block.type, items };
  }
  if (block.type === "checklist" && Array.isArray(block.items)) {
    const items = block.items.map((item) => cleanText(item, 420)).filter(Boolean);
    if (!items.length) return null;
    return { type: "checklist", items };
  }
  if (
    (block.type === "table" || block.type === "rubric" || block.type === "timeline" || block.type === "responsibility_matrix") &&
    Array.isArray(block.headers) &&
    Array.isArray(block.rows)
  ) {
    const headers = block.headers.map((item) => cleanText(item, 120)).filter(Boolean);
    const rows = block.rows
      .filter(Array.isArray)
      .map((row) => row.map((cell) => cleanText(cell, 240)).slice(0, Math.max(headers.length, 1)))
      .filter((row) => row.some(Boolean));
    if (!headers.length || !rows.length) return null;
    return { type: block.type, headers, rows } as WordBlock;
  }
  if (block.type === "callout" && typeof block.text === "string" && cleanText(block.text, 1200)) {
    return { type: "callout", title: cleanText(block.title, 80) || undefined, text: cleanText(block.text, 1200) };
  }
  return null;
}

function isWordDocumentType(value: unknown): value is WordDocumentType {
  return (
    value === "lesson_plan" ||
    value === "course_plan" ||
    value === "report" ||
    value === "proposal" ||
    value === "business_plan" ||
    value === "work_summary" ||
    value === "research_summary" ||
    value === "contract" ||
    value === "notice" ||
    value === "meeting_minutes" ||
    value === "training_plan" ||
    value === "summary" ||
    value === "general"
  );
}

function normalizeWordDocumentPlan(value: unknown): WordDocumentPlan | null {
  const plan = value as Partial<WordDocumentPlan> | null;
  if (!plan || typeof plan !== "object") return null;
  const title = cleanText(plan.title, 80);
  if (!title || !Array.isArray(plan.sections)) return null;
  const documentType = isWordDocumentType(plan.documentType) ? plan.documentType : undefined;
  const sections = plan.sections
    .map((rawSection): WordSection | null => {
      const section = rawSection as Partial<WordSection> | null;
      if (!section || typeof section !== "object") return null;
      const heading = cleanText(section.heading, 120);
      if (!heading) return null;
      const blocks = Array.isArray(section.blocks) ? section.blocks.map(normalizeWordBlock).filter((block): block is WordBlock => Boolean(block)) : [];
      const intro = cleanText(section.intro, 1200) || undefined;
      if (!intro && !blocks.length) return null;
      const rawLevel = Number(section.level || 1);
      const level = (rawLevel === 2 || rawLevel === 3 || rawLevel === 4 ? rawLevel : 1) as 1 | 2 | 3 | 4;
      return { heading, level, intro, blocks };
    })
    .filter((section): section is WordSection => section !== null);
  if (!sections.length) return null;
  return {
    title,
    subtitle: cleanText(plan.subtitle, 120) || undefined,
    documentType,
    sections
  };
}

export function parseWordDocumentPlanJson(markdown: string): WordDocumentPlan | null {
  if (!String(markdown || "").includes(WORD_PLAN_JSON_MARKER) && !String(markdown || "").trim().startsWith("{")) return null;
  const jsonText = extractJsonObject(markdown);
  if (!jsonText) return null;
  try {
    return normalizeWordDocumentPlan(JSON.parse(jsonText));
  } catch {
    return null;
  }
}

export function serializeWordDocumentPlan(plan: WordDocumentPlan) {
  return `${WORD_PLAN_JSON_MARKER}\n${JSON.stringify(plan)}`;
}

function documentTypeFromTemplate(template: DocumentTemplate): WordDocumentPlan["documentType"] {
  if (template === "lesson_plan") return "lesson_plan";
  if (template === "report") return "report";
  if (template === "proposal") return "proposal";
  if (template === "meeting_minutes") return "meeting_minutes";
  if (template === "formal_doc") return "general";
  return "general";
}

function inferTitle(fallbackTitle: string, blocks: MarkdownBlock[]) {
  const firstHeading = blocks.find((block) => block.type === "heading");
  return cleanText(firstHeading?.text || fallbackTitle || "正式文档", 80);
}

function uniqueTexts(items: string[]) {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const item of items.map((value) => cleanText(value, 80)).filter(Boolean)) {
    if (seen.has(item)) continue;
    seen.add(item);
    result.push(item);
  }
  return result;
}

function uniqueIntentSource(...parts: Array<string | undefined>) {
  const seen = new Set<string>();
  return parts
    .map((part) => String(part || "").trim())
    .filter((part) => {
      const key = normalizeText(part);
      if (!key || seen.has(key)) return false;
      seen.add(key);
      return true;
    })
    .join("\n");
}

const TASK_WORDS =
  /^(?:请|帮我|麻烦|给我|生成|写|写一份|写一个|写个|做|做一份|做一个|制作|起草|输出|导出|整理|撰写|设计|创建|一份|一个|一篇|这个|这份)+/;

const DOCUMENT_TYPE_WORDS =
  /(教案|教学设计|教学方案|课时设计|课程设计|课程方案|课程计划|调研报告|分析报告|研究报告|报告|实施方案|建设方案|项目方案|商业计划书|创业计划书|商业计划|方案书|方案|工作总结|季度总结|年度总结|月度总结|周报|总结|研究综述|文献综述|研究总结|摘要|合同|协议|通知|公告|会议纪要|会议记录|培训计划|文档|文件|Word|word|docx)$/;

function cleanIntentText(value: string) {
  let cleaned = cleanText(value, 240)
    .replace(/^#+\s*/g, "")
    .replace(/[“”"《》]/g, " ")
    .replace(/\b(word|docx|document)\b/gi, " ")
    .replace(/[，。；;、,.!?！？:：]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
  while (TASK_WORDS.test(cleaned)) {
    cleaned = cleaned.replace(TASK_WORDS, "").trim();
  }
  return cleaned.replace(DOCUMENT_TYPE_WORDS, "").replace(/的$/, "").trim();
}

function detectIntentDocumentType(text: string): WordGenerationIntent["documentType"] {
  const normalized = normalizeText(text);
  if (/会议纪要|会议记录|minutes/.test(normalized)) return "meeting_minutes";
  if (/教案|教学设计|课时设计|授课/.test(normalized)) return "lesson_plan";
  if (/课程方案|课程计划|课程建设|课程设计/.test(normalized)) return "course_plan";
  if (/培训计划|培训方案|培训安排/.test(normalized)) return "training_plan";
  if (/商业计划书|创业计划书|商业计划|businessplan/.test(normalized)) return "business_plan";
  if (/方案书|项目方案|实施方案|建设方案|proposal/.test(normalized)) return "proposal";
  if (/工作总结|季度总结|年度总结|月度总结|周报|复盘总结/.test(normalized)) return "work_summary";
  if (/研究综述|文献综述|研究总结|researchsummary|literaturereview/.test(normalized)) return "research_summary";
  if (/通知|公告|notice/.test(normalized)) return "notice";
  if (/合同|协议|contract/.test(normalized)) return "contract";
  if (/总结|摘要|小结|summary/.test(normalized)) return "summary";
  if (/报告|调研|分析|report/.test(normalized)) return "report";
  return "general";
}

function extractAudience(text: string) {
  const match =
    text.match(/(?:授课对象|适用对象|对象|面向|适合|适用于)(?:为|是|：|:)?\s*([^，。；;\n]{2,40})/) ||
    text.match(/给(?!我)([^，。；;\n]{2,32}?(?:学生|学员|学习者|教师|员工|团队|班级|部门|社团|管理层|用户|客户))/);
  return cleanText(match?.[1], 50)
    .replace(/^(为|是)\s*/, "")
    .replace(/(?:要求|范围|周期|课时).*$/, "")
    .trim() || undefined;
}

function extractExplicitRequirements(text: string) {
  const requirementMatch = text.match(/(?:要求|需要|必须|包含|包括|覆盖|重点写|重点讲|重点说明|列出)([：:\s]?)([^。；;\n]+)/);
  const explicit = requirementMatch?.[2] ? requirementMatch[2] : "";
  const styleMatches = [...text.matchAll(/内容要([^，。；;\n]+)/g)].map((match) => match[1]);
  return [explicit, ...styleMatches]
    .filter(Boolean)
    .join("、")
    .split(/[、,，/；;和与]/)
    .map((item) => cleanText(item, 60).replace(/^(?:要求|需要|必须|覆盖|包含|包括|列出|说明|突出|聚焦|内容要)+/, "").trim())
    .filter((item) => item.length >= 2);
}

function extractPurpose(text: string) {
  const match = text.match(/(?:目的|用途|用于|用来|目标)(?:是|为|：|:)?\s*([^，。；;\n]{2,80})/);
  return cleanIntentText(match?.[1] || "")
    .replace(/^(?:实现|完成|达成)/, "")
    .replace(/(?:范围|对象|面向|要求|周期|课时|篇幅|页数).*$/, "")
    .trim() || undefined;
}

function extractLengthRequirement(text: string) {
  const match =
    text.match(/(?:篇幅|页数|字数|控制在|约|大约|不少于|不超过)?\s*((?:\d+|[一二三四五六七八九十两]+)\s*(?:页|字|千字|万字)(?:以内|左右|以上|以下)?)/) ||
    text.match(/(?:篇幅|页数|字数)(?:为|是|：|:)?\s*([^，。；;\n]{2,24})/);
  return cleanText(match?.[1], 40).replace(/\s+/g, "") || undefined;
}

function extractStyleRequirement(text: string) {
  const matches = [
    ...text.matchAll(/(?:风格|文风|语气|内容)(?:要|要求|保持|为|是|：|:)?\s*([^，。；;\n]{2,40})/g)
  ].map((match) => cleanText(match[1], 40));
  const inline = [
    /正式/.test(text) ? "正式" : "",
    /专业/.test(text) ? "专业" : "",
    /简洁|精简/.test(text) ? "简洁" : "",
    /详细|完整/.test(text) ? "详细完整" : "",
    /可直接(?:使用|交付|提交)/.test(text) ? "可直接使用" : ""
  ].filter(Boolean);
  return uniqueTexts([...matches, ...inline]).join("、") || undefined;
}

function splitScopeItems(value?: string) {
  return cleanText(value, 160)
    .replace(/^(包括|包含|是|为|：|:)\s*/, "")
    .split(/[、,，/；;]/)
    .map((item) => cleanText(item, 50))
    .filter((item) => item.length >= 2);
}

function extractDuration(text: string) {
  const match =
    text.match(/(?:会议时间|时间)(?:为|是|：|:)?\s*((?:\d{4}年)?\d{1,2}月\d{1,2}日(?:[^\s，。；;\n]{0,12})?)/) ||
    text.match(/(?:课时|时长|周期|工期|期限|持续时间|会议时间|培训周期|执行周期)?\s*((?:\d+|[一二三四五六七八九十两]+)\s*(?:课时|学时|小时|分钟|天|周|个月|月)(?:以内|左右|以上)?)/) ||
    text.match(/(?:周期|工期|期限|会议时间|培训周期|执行周期)(?:为|是|：|:)?\s*([^\s，。；;\n]{2,24})/);
  return cleanText(match?.[1], 30).replace(/\s+/g, "") || undefined;
}

function extractScope(text: string) {
  const match =
    text.match(/(?:范围|内容范围|议题)(?:包括|包含|是|为|：|:)?\s*([^。；;\n]+?)(?=，?(?:面向|对象|授课对象|要求|周期|课时|篇幅|页数|会议时间|参会对象)|[。；;\n]|$)/) ||
    text.match(/(?:围绕|聚焦|关于)([^，。；;\n]{2,60})/);
  return cleanText(match?.[1], 100)
    .replace(/\s*(?:\d+|[一二三四五六七八九十两]+)\s*(?:课时|学时|小时|分钟|天|周|个月|月|页|字)(?:以内|左右|以上)?.*$/, "")
    .replace(/的$/, "")
    .trim() || undefined;
}

function extractChapterTitle(text: string, chapter?: string) {
  if (!chapter) return undefined;
  const escaped = chapter.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  const match = text.match(new RegExp(`${escaped}\\s*(?:[:：、\\-—]?\\s*)([^，。；;\\n]{2,40})`));
  const value = cleanText(match?.[1], 50)
    .replace(/\s*(?:\d+|[一二三四五六七八九十两]+)\s*(?:课时|学时|小时|分钟|天|周|个月|月|页|字)(?:以内|左右|以上)?.*$/, "")
    .replace(/(?:课时|授课对象|对象|面向|要求|范围|内容要|可直接交付|正式).*$/, "")
    .replace(DOCUMENT_TYPE_WORDS, "")
    .trim()
    .replace(/(?:教学|课程|课堂)?的?(?:教案|教学设计|教学方案)?$/, "")
    .trim();
  return value || undefined;
}

function extractQuotedTopic(text: string) {
  const match = text.match(/《([^》]{2,80})》/);
  return cleanText(match?.[1], 80) || undefined;
}

function inferAnimationRequirements(text: string) {
  if (!/三维动画|3d动画|动画规律|动画|关键帧|缓入缓出|挤压拉伸/i.test(text)) return [];
  return ["关键帧", "运动规律", "动画节奏", "缓入缓出", "挤压拉伸"];
}

function inferTopic({
  rawText,
  cleaned,
  quotedTopic,
  chapterMatch,
  scope,
  duration,
  audience
}: {
  rawText: string;
  cleaned: string;
  quotedTopic?: string;
  chapterMatch?: RegExpMatchArray | null;
  scope?: string;
  duration?: string;
  audience?: string;
}) {
  if (quotedTopic) return cleanIntentText(quotedTopic) || cleanText(quotedTopic, 60);
  let candidate = chapterMatch ? cleaned.slice(0, chapterMatch.index).trim() : cleaned;
  for (const marker of ["范围", "面向", "对象", "授课对象", "要求", "周期", "课时", "篇幅", "页数"]) {
    const index = candidate.indexOf(marker);
    if (index > 0) candidate = candidate.slice(0, index).trim();
  }
  for (const value of [scope, duration, audience]) {
    if (value) candidate = candidate.replace(value, " ");
  }
  candidate = cleanIntentText(candidate);
  if (!candidate || candidate.length < 2) {
    const beforeType = rawText.match(/(?:生成|写|撰写|制作|设计|做一份)?\s*([^，。；;\n《》]{2,50}?)(?:教案|报告|方案|总结|合同|文档)/);
    candidate = cleanIntentText(beforeType?.[1] || "");
  }
  return cleanText(candidate, 60) || "文档主题";
}

function buildKeywords(intent: Omit<WordGenerationIntent, "keywords">, rawText: string) {
  const base = [
    intent.topic,
    intent.purpose,
    intent.chapter,
    intent.chapterTitle,
    ...splitScopeItems(intent.scope),
    intent.duration,
    intent.lengthRequirement,
    intent.audience,
    ...intent.mustInclude,
    ...intent.requirements,
    ...inferAnimationRequirements(`${intent.topic} ${intent.scope || ""} ${rawText}`)
  ];
  return uniqueTexts(
    base
      .flatMap((item) => splitScopeItems(item || ""))
      .concat(base.filter(Boolean) as string[])
      .map((item) => cleanIntentText(item))
      .filter((item) => item.length >= 2 && !/^(教案|报告|方案|总结|文档|课时|页数)$/.test(item))
  ).slice(0, 20);
}

export function extractWordGenerationIntent(rawPrompt: string): WordGenerationIntent {
  const text = String(rawPrompt || "").replace(/\r\n/g, "\n");
  const documentType = detectIntentDocumentType(text);
  const quotedTopic = extractQuotedTopic(text);
  const cleaned = cleanIntentText(text);
  const chapterMatch = cleaned.match(/第[一二三四五六七八九十百千万\d]+章节?|第[一二三四五六七八九十百千万\d]+章|第[一二三四五六七八九十百千万\d]+节/);
  const chapter = cleanText(chapterMatch?.[0], 24) || undefined;
  const chapterTitle = extractChapterTitle(cleaned, chapter);
  const scope = extractScope(text) || chapterTitle;
  const duration = extractDuration(text);
  const lengthRequirement = extractLengthRequirement(text);
  const audience = extractAudience(text);
  const purpose = extractPurpose(text);
  const styleRequirement = extractStyleRequirement(text);
  const topic = inferTopic({ rawText: text, cleaned, quotedTopic, chapterMatch, scope, duration, audience });
  const mustInclude = uniqueTexts([
    ...extractExplicitRequirements(text),
    ...(chapter && !chapterTitle ? [`突出${chapter}`] : []),
    ...inferAnimationRequirements(`${topic} ${scope || ""} ${text}`)
  ]);
  const withoutKeywords = {
    documentType,
    topic,
    purpose,
    audience,
    scope,
    chapter,
    chapterTitle,
    duration,
    lengthRequirement,
    styleRequirement,
    mustInclude,
    requirements: mustInclude
  };

  return {
    ...withoutKeywords,
    keywords: buildKeywords(withoutKeywords, text)
  };
}

function shouldKeepNumberedList(sectionHeading: string, items: string[]) {
  const text = normalizeText(sectionHeading);
  return /步骤|流程|过程|安排|标准|评分|procedure|process|step|timeline|criteria/.test(text);
}

function shouldUseBulletList(sectionHeading: string) {
  const text = normalizeText(sectionHeading);
  return /目标|准备|材料|清单|任务|要点|重点|难点|要求|objective|material|task|checklist|point/.test(text);
}

function listToBlocks(sectionHeading: string, ordered: boolean, items: string[]): WordBlock[] {
  const cleaned = items.map((item) => cleanText(item, 180)).filter(Boolean);
  if (!cleaned.length) return [];
  if (ordered && shouldKeepNumberedList(sectionHeading, cleaned)) return [{ type: "numbered_list", items: cleaned }];
  if (shouldUseBulletList(sectionHeading) || cleaned.length <= 4) return [{ type: "bullet_list", items: cleaned }];
  return cleaned.map((item) => ({ type: "paragraph", text: item }) as WordBlock);
}

function tableBlock(rows: string[][]): WordBlock | null {
  const cleanedRows = rows
    .map((row) => row.map((cell) => cleanText(cell, 120)))
    .filter((row) => row.some(Boolean));
  if (cleanedRows.length < 2) return null;
  return {
    type: "table",
    headers: cleanedRows[0],
    rows: cleanedRows.slice(1)
  };
}

function lessonProcessTableFromMarkdown(block: WordBlock, sectionHeading: string): WordBlock {
  if (block.type !== "table" || !/教学过程/.test(sectionHeading)) return block;
  const headersText = block.headers.join(" ");
  if (/教师活动/.test(headersText) && /学生活动/.test(headersText) && /设计意图/.test(headersText)) return block;
  const rows = block.rows.length ? block.rows : [["导入", "案例观察", "10 分钟"]];
  return {
    type: "table",
    headers: ["教学环节", "时间", "教师活动", "学生活动", "设计意图"],
    rows: rows.map((row, index) => {
      const stage = cleanText(row[0], 40) || (index === 0 ? "任务导入" : `活动${index + 1}`);
      const content = cleanText(row[1], 80) || cleanText(row.join(" "), 80) || "课堂任务";
      const time = cleanText(row[2], 30) || "按课堂节奏";
      return [
        stage,
        time,
        `围绕${content}组织示范、追问和即时反馈。`,
        `观察${content}材料，完成记录、讨论或练习输出。`,
        `让学生把${content}转化为可说明、可检查的学习成果。`
      ];
    })
  };
}

function fallbackIntro(heading: string, title: string) {
  const cleanHeading = stripHeadingNumber(heading);
  return `${cleanHeading}部分用于说明“${title}”的关键背景、主要内容和交付要求，帮助读者先建立整体理解，再阅读后续细节。`;
}

function ensureSectionNarrative(section: WordSection, title: string): WordSection {
  const hasNarrative = Boolean(section.intro) || section.blocks.some((block) => block.type === "paragraph");
  if (hasNarrative) return section;
  return {
    ...section,
    intro: fallbackIntro(section.heading, title)
  };
}

export function isUsableWordIntent(intent: WordGenerationIntent) {
  const topic = cleanIntentText(intent.topic);
  return Boolean(topic && topic !== "文档主题" && topic.length >= 2 && !/^(教案|报告|方案|总结|文档|文件)$/.test(topic));
}

function documentTypeFromIntent(intent: WordGenerationIntent, template: DocumentTemplate): WordDocumentPlan["documentType"] {
  if (intent.documentType !== "general") return intent.documentType;
  return documentTypeFromTemplate(template);
}

function cleanTitlePart(value?: string) {
  return cleanIntentText(value || "").replace(/^(聚焦|突出|覆盖|包含|包括|列出)/, "").trim();
}

function isDeliveryOrStyleRequirement(value?: string) {
  const text = cleanTitlePart(value);
  if (!text) return false;
  return /^(?:正式|专业|完整|规范|严谨|可直接交付|直接交付|可直接使用|直接使用|可修改|内容正式|条理清晰|结构清晰)$/.test(text);
}

function isSyntheticChapterRequirement(value?: string) {
  return /^突出第[一二三四五六七八九十百千万\d]+章节?$/.test(cleanTitlePart(value));
}

function makeTitleFromIntent(intent: WordGenerationIntent, suffix: string) {
  const shouldIncludeFocus = Boolean(intent.chapter) || intent.documentType === "lesson_plan" || intent.documentType === "course_plan" || intent.documentType === "training_plan";
  const parts = uniqueTexts([intent.topic, intent.chapter, shouldIncludeFocus ? intent.chapterTitle || intent.scope : undefined].map(cleanTitlePart).filter(Boolean));
  const title = `${parts.join(" ")}${suffix}`.replace(/\s+/g, " ").trim();
  return cleanText(title, 40);
}

function displayValue(value: string | undefined, fallback: string) {
  return cleanText(value, 80) || fallback;
}

function keywordList(intent: WordGenerationIntent, fallback: string[] = []) {
  const identity = new Set(
    [intent.topic, intent.chapter, intent.duration, intent.audience]
      .map((item) => normalizeText(cleanTitlePart(item)))
      .filter(Boolean)
  );
  return uniqueTexts([
    ...fallback,
    ...intent.mustInclude,
    ...intent.requirements,
    ...splitScopeItems(intent.scope),
    ...(intent.keywords || [])
  ]
    .map(cleanTitlePart)
    .filter((item) => item && !identity.has(normalizeText(item)) && !isDeliveryOrStyleRequirement(item) && !isSyntheticChapterRequirement(item)))
    .slice(0, 14);
}

function keywordText(intent: WordGenerationIntent, fallback: string[] = []) {
  const keywords = keywordList(intent, fallback);
  return keywords.length ? keywords.join("、") : focusText(intent);
}

function focusText(intent: WordGenerationIntent) {
  return cleanText(intent.chapterTitle || intent.scope || intent.chapter || intent.topic, 80);
}

function scopeItems(intent: WordGenerationIntent) {
  return splitScopeItems(intent.scope).length ? splitScopeItems(intent.scope) : keywordList(intent).filter((item) => item !== intent.topic).slice(0, 4);
}

function readableList(items: string[], fallback: string) {
  const cleaned = uniqueTexts(items.map(cleanTitlePart).filter(Boolean));
  return cleaned.length ? cleaned.join("、") : fallback;
}

function contentAnchors(intent: WordGenerationIntent, fallback: string[] = []) {
  const identity = new Set(
    [intent.topic, intent.chapter, intent.duration, intent.audience]
      .map((item) => normalizeText(cleanTitlePart(item)))
      .filter(Boolean)
  );
  return uniqueTexts([
    ...splitScopeItems(intent.scope),
    ...intent.mustInclude,
    ...intent.requirements,
    ...(intent.keywords || []),
    ...fallback
  ]
    .map(cleanTitlePart)
    .filter(
      (item) =>
        item &&
        !identity.has(normalizeText(item)) &&
        !isDeliveryOrStyleRequirement(item) &&
        !isSyntheticChapterRequirement(item) &&
        !/^(教案|报告|方案|总结|文档|文件|课时|页数)$/.test(item)
    ))
    .slice(0, 14);
}

function anchorText(intent: WordGenerationIntent, fallback: string[] = []) {
  return readableList(contentAnchors(intent, fallback), focusText(intent));
}

function scopeOrAnchors(intent: WordGenerationIntent, fallback: string[] = []) {
  const scopes = scopeItems(intent);
  return scopes.length ? scopes : contentAnchors(intent, fallback).slice(0, 4);
}

function withTopic(item: string, topic: string) {
  return `${item}在${topic}中的表现`;
}

function lessonProcessRows({
  intent,
  topic,
  focus,
  conceptPair,
  practicePair,
  practiceFocus,
  evaluationTerms,
  duration
}: {
  intent: WordGenerationIntent;
  topic: string;
  focus: string;
  conceptPair: string;
  practicePair: string;
  practiceFocus: string;
  evaluationTerms: string;
  duration: string;
}) {
  const domainText = normalizeText(`${topic} ${focus} ${intent.mustInclude.join(" ")} ${intent.requirements.join(" ")} ${intent.keywords.join(" ")}`);
  if (/动画|关键帧|缓入缓出|挤压拉伸|运动规律|三维/.test(domainText)) {
    return {
      intro: `教学过程以“观察运动片段、拆解${conceptPair}、调试${practicePair}、展示修正结果”为主线，让学习者在${duration}内把${focus}落实到可观察的画面变化中。`,
      rows: [
        ["运动观察", "约10%", `播放或展示${topic}中的短片段，暂停关键动作，追问${conceptPair}如何影响运动判断。`, `记录片段中${focus}最明显的变化点，并说出初步依据。`, "用真实画面唤起问题意识，让学生先看到运动差异。"],
        ["规律拆解", "约25%", `按时间轴拆解${conceptPair}，说明位置、速度、节奏和视觉重量之间的关系。`, `在示例时间轴上标注${conceptPair}，补充不理解的节点。`, "把抽象术语转化为可标注、可讨论的分析对象。"],
        ["技法示范", "约20%", `现场演示${practicePair}的调整过程，对比调整前后的动作可信度。`, `跟随示范完成一组参数或画面标注，说明变化原因。`, "通过前后对比建立操作方法，而不是停留在定义记忆。"],
        ["片段练习", "约30%", `布置${focus}短练习，要求结果中清楚体现${practiceFocus}。`, `完成短片段或分镜标注，依据评价标准自查并修改。`, "让学生把观察结论转化为可提交的作品或分析结果。"],
        ["展示复盘", "约15%", `围绕${evaluationTerms}点评学生输出，指出动作节奏、可信度和表达清晰度的改进点。`, "展示自己的判断依据，记录下一轮修改方向。", "用展示和反馈巩固迁移能力。"]
      ]
    };
  }
  if (/写作|语文|描写|作文|阅读|文本|段落/.test(domainText)) {
    return {
      intro: `教学过程以“文本感知、技法辨析、片段改写、同伴评议”为主线，让学习者在${duration}内把${focus}转化为能写出来、能说明理由的表达能力。`,
      rows: [
        ["文本唤醒", "约10%", `呈现与${focus}相关的短文本，追问${conceptPair}如何塑造读者印象。`, `圈画文本中触动自己的语句，说明人物或场景给人的第一印象。`, "先从阅读体验进入写作问题，降低技法讲解的距离感。"],
        ["技法辨析", "约25%", `拆解${conceptPair}的表达位置、语言特征和常见薄弱点。`, `比较两组表达效果，判断哪一组更能服务${focus}。`, "让学生理解写作技法和表达目的之间的关系。"],
        ["示范改写", "约20%", `用同一素材示范加入${practicePair}后的变化，说明改写取舍。`, `跟随示范改写一个句群，并标注自己使用的技法。`, "通过可见的改写过程，把知识点转化为写作动作。"],
        ["片段写作", "约30%", `布置${topic}的${focus}片段任务，要求自然使用${practiceFocus}。`, "完成一段短文，依据评价表检查细节是否具体、情感是否可信。", "把课堂理解落实到独立表达。"],
        ["互评升格", "约15%", `围绕${evaluationTerms}组织同伴互评，选取一处句子进行现场升格。`, "说明自己修改前后的变化，并记录可迁移的写作方法。", "用评价和二次修改巩固写作策略。"]
      ]
    };
  }
  return {
    intro: `教学过程按“进入任务情境、拆解${conceptPair}、示范${practicePair}、实践输出、评价总结”推进，使学习者在${duration}内形成完整学习闭环。`,
    rows: [
      ["任务导入", "约10%", `呈现${topic}中与${focus}相关的任务情境，提出需要解决的核心问题。`, `观察材料，记录对${focus}的初步判断。`, "激活已有经验，明确学习方向。"],
      ["要点拆解", "约25%", `围绕${conceptPair}讲解判断依据、表现特征和常见误区。`, `梳理${conceptPair}之间的关系，提出不理解的问题。`, "建立可迁移的知识框架。"],
      ["方法示范", "约20%", `选择典型材料分步处理${practicePair}，展示从判断到执行的过程。`, `跟随示范完成${focus}标注、比较和说明。`, "把抽象要求变成可执行方法。"],
      ["实践输出", "约30%", `布置${topic}的${focus}练习，要求学生在结果中体现${practiceFocus}。`, "完成任务输出，依据评价标准自查并修改。", "形成独立应用能力。"],
      ["评价迁移", "约15%", `围绕${evaluationTerms}组织展示、互评和教师点评，归纳改进点。`, "说明自己的任务依据和后续修正方向。", "巩固学习结果，形成课后迁移。"]
    ]
  };
}

function wantsCompleteCourseLesson(intent: WordGenerationIntent) {
  const text = normalizeText([
    intent.topic,
    intent.scope,
    intent.chapter,
    intent.chapterTitle,
    ...intent.mustInclude,
    ...intent.requirements,
    ...intent.keywords
  ].filter(Boolean).join(" "));
  return /完整课程教案|课程级|课程教案|课程目标|教学安排|单元示例|评价方案|学生提交清单/.test(text);
}

function buildLessonPlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const title = makeTitleFromIntent(intent, "教案");
  const rawFocus = focusText(intent);
  const anchors = contentAnchors(intent, [rawFocus]).filter((item) => normalizeText(item) !== normalizeText(rawFocus));
  const focus = cleanText(intent.chapterTitle || intent.scope || readableList(anchors.slice(0, 2), rawFocus), 80);
  const anchorsText = readableList(anchors, focus);
  const conceptPair = readableList(anchors.slice(0, 2), focus);
  const practicePair = readableList(anchors.slice(2, 4), conceptPair);
  const evaluationTerms = readableList([anchors[0], anchors[1], anchors[2]].filter(Boolean), conceptPair);
  const duration = displayValue(intent.duration, "按教学安排");
  const audience = displayValue(intent.audience, "目标学习者");
  const chapter = displayValue(intent.chapter, "相关章节");
  const topic = intent.topic;
  const practiceFocus = readableList(anchors.slice(0, 3), focus);
  const process = lessonProcessRows({ intent, topic, focus, conceptPair, practicePair, practiceFocus, evaluationTerms, duration });
  const completeCourseLesson = wantsCompleteCourseLesson(intent);
  const completeCourseSections: WordSection[] = completeCourseLesson
    ? [
        {
          heading: "教学方法",
          level: 1,
          intro: `教学方法围绕${topic}的课程目标组织，采用任务驱动、案例分析、示范练习和展示反馈结合的方式，确保${audience}能够把${focus}转化为可完成、可评价的学习成果。`,
          blocks: [
            {
              type: "bullet_list",
              items: [
                `任务驱动：围绕${focus}设置递进任务，让学习者在完成任务时理解${conceptPair}。`,
                `案例分析：使用与${topic}相关的典型材料，引导学生比较${practicePair}的效果差异。`,
                `展示反馈：通过课堂展示、同伴互评和教师点评修正${practiceFocus}相关问题。`
              ]
            }
          ]
        },
        {
          heading: "教学安排与课程内容",
          level: 1,
          intro: `教学安排把${topic}拆分为可推进的课程内容，围绕${focus}安排导入、讲解、练习、展示和评价，避免只停留在概念介绍。`,
          blocks: [
            {
              type: "timeline",
              headers: ["阶段", "时间", "课程内容", "学习产出"],
              rows: [
                ["课程导入", "约10%", `观察${topic}中与${focus}相关的材料，提出本课核心问题。`, `形成${focus}观察记录。`],
                ["知识建构", "约25%", `讲解${conceptPair}的判断依据、表现特征和常见误区。`, `完成知识点标注或概念说明。`],
                ["单元练习", "约40%", `围绕${practicePair}完成分组或个人任务。`, `提交能够体现${practiceFocus}的阶段成果。`],
                ["展示评价", "约25%", `按评价方案组织展示、互评、教师点评和修改。`, `提交修订说明和最终成果。`]
              ]
            }
          ]
        },
        {
          heading: "单元示例教案",
          level: 1,
          intro: `单元示例以${focus}为核心，把${conceptPair}和${practicePair}落到一节可执行的课堂流程中，便于教师直接改写为实际授课方案。`,
          blocks: [
            {
              type: "table",
              headers: ["教学环节", "时间", "教师活动", "学生活动", "设计意图"],
              rows: [
                ["单元导入", "5-8分钟", `出示${topic}中与${focus}相关的单元任务成品或过程材料，明确本单元需要解决的问题。`, `观察材料并记录${conceptPair}中最需要弄清楚的一个点。`, "让学生先看到单元任务的完整目标，再进入知识学习。"],
                ["要点建构", "15-20分钟", `围绕${conceptPair}讲解判断依据，并用对比材料说明错误处理会造成的结果。`, `在示例材料上完成标注，说明${focus}的判断理由。`, "把单元知识点转化为可观察、可说明的分析依据。"],
                ["任务推进", "25-35分钟", `分步示范${practicePair}的处理过程，提示学生保留过程记录。`, `完成单元任务初稿，并记录遇到的困难和修改依据。`, "让学生在实践中形成可提交、可反馈的阶段成果。"],
                ["展示修订", "10-15分钟", `依据评价方案选择典型成果进行点评，指出${evaluationTerms}的改进方向。`, "展示成果，完成自评和同伴建议记录。", "用评价反馈推动成果二次修改，而不是只完成一次性作业。"]
              ]
            }
          ]
        },
        {
          heading: "综合项目或课堂任务",
          level: 1,
          intro: `综合项目要求学生围绕${topic}完成与${focus}直接相关的作品、分析或展示任务，任务成果必须能够体现${evaluationTerms}。`,
          blocks: [
            {
              type: "bullet_list",
              items: [
                `任务主题：围绕${topic}设计一项${focus}练习或分析任务。`,
                `过程要求：记录${conceptPair}的判断依据，并说明如何处理${practicePair}。`,
                `成果要求：提交最终成果、过程说明和自我修订记录。`
              ]
            }
          ]
        },
        {
          heading: "评价方案",
          level: 1,
          intro: `评价方案兼顾过程表现、学习成果和反思改进，重点判断学生是否真正理解并能运用${focus}相关知识。`,
          blocks: [
            {
              type: "rubric",
              headers: ["评价项目", "比例", "评价标准"],
              rows: [
                ["课堂参与", "建议20%（可按实际调整）", `能围绕${conceptPair}提出问题、参与讨论并完成课堂记录。`],
                ["任务成果", "建议45%（可按实际调整）", `成果清楚体现${practicePair}，并能说明与${focus}的关系。`],
                ["展示表达", "建议20%（可按实际调整）", `展示时能说明判断依据、修改过程和${evaluationTerms}的落实情况。`],
                ["反思改进", "建议15%（可按实际调整）", `能依据评价反馈提出具体修订点，而不是只做笼统总结。`]
              ]
            }
          ]
        },
        {
          heading: "学生提交清单",
          level: 1,
          intro: `学生提交清单用于确保${audience}在课程结束后能够提交完整、可评价、可复盘的学习材料。`,
          blocks: [
            {
              type: "checklist",
              items: [
                `${focus}课堂观察或分析记录`,
                `体现${practicePair}的任务成果`,
                `围绕${conceptPair}的过程说明`,
                `根据评价方案完成的自评与修改记录`,
                `最终提交文件或展示材料`
              ]
            }
          ]
        }
      ]
    : [];

  return {
    title,
    subtitle: `${displayValue(intent.chapter, "课程章节")}课堂设计`,
    documentType: "lesson_plan",
    sections: [
      {
        heading: "课程基本信息",
        level: 1,
        intro: `本教案以“${topic}”为课程主题，在${chapter}将“${focus}”作为课堂主线，面向${audience}组织${duration}的学习活动。课堂内容把${anchorsText}转化为观察指标、示范步骤和练习结果。`,
        blocks: [
          {
            type: "table",
            headers: ["项目", "内容"],
            rows: [
              ["课程名称", topic],
              ["章节主题", `${chapter} ${focus}`],
              ["授课对象", audience],
              ["课时", duration],
              ["课程性质", `${focus}知识讲解与任务训练结合`],
              ["授课方式", `${conceptPair}讲解、${practicePair}示范、练习与反馈`]
            ]
          }
        ]
      },
      {
        heading: "设计思路",
        level: 1,
        intro: `本课从${topic}的真实学习任务进入，先让学生观察${focus}在案例中的表现，再把${conceptPair}拆成可判断的观察点，最后通过${practicePair}练习形成可修改、可展示的课堂成果。`,
        blocks: [
          {
            type: "paragraph",
            text: `教学设计强调“观察依据—方法示范—实践修正”的连续过程：教师不只讲概念，而是让${audience}在${duration}内经历发现问题、标注依据、尝试操作和复盘反馈，确保${anchorsText}都能落到具体学习活动中。`
          }
        ]
      },
      {
        heading: completeCourseLesson ? "课程目标与教学目标" : "教学目标",
        level: 1,
        intro: `教学目标围绕${focus}展开，要求学习者把${conceptPair}的理解转化为观察、分析和表达。`,
        blocks: [
          {
            type: "bullet_list",
            items: [
              `知识目标：说明${focus}中${conceptPair}的含义，并解释它们如何影响${topic}的学习判断。`,
              `能力目标：围绕${practicePair}完成案例观察、问题拆解和课堂练习输出。`,
              `素养目标：用证据说明自己的判断依据，根据同伴和教师反馈修正${focus}相关成果。`
            ]
          }
        ]
      },
      {
        heading: "教学重点与难点",
        level: 1,
        intro: `${focus}的教学重点在于把${conceptPair}与${practicePair}之间的关系讲清楚，难点在于让学习者把这些判断迁移到${topic}的实际练习中。`,
        blocks: [
          { type: "paragraph", text: `教学重点：围绕${conceptPair}建立分析框架，使学习者能说明它们在${focus}中的作用和相互影响。` },
          { type: "paragraph", text: `教学难点：学习者可能能说出${practicePair}，却难以在作品观察或练习操作中稳定运用；教师需要用对比材料、分步示范和即时反馈把理解落实为方法。` }
        ]
      },
      {
        heading: "教学准备",
        level: 1,
        intro: `教学准备直接服务${topic}的${focus}学习，材料、工具和任务都围绕${conceptPair}与${practicePair}组织。`,
        blocks: [
          {
            type: "bullet_list",
            items: [
              `教学资料：准备能呈现${conceptPair}差异的演示材料，并标注可观察、可比较的分析点。`,
              `软件环境：准备${topic}课堂展示、学生练习和结果提交所需的工具环境。`,
              `案例素材：选择能够体现${practicePair}的片段或练习素材，用于导入、分析和复盘。`,
              `课堂任务：设计可在${duration}内完成的${focus}练习，并配套与${practiceFocus}对应的评价标准。`
            ]
          }
        ]
      },
      ...completeCourseSections,
      {
        heading: "教学过程",
        level: 1,
        intro: process.intro,
        blocks: [
          {
            type: "table",
            headers: ["教学环节", "时间", "教师活动", "学生活动", "设计意图"],
            rows: process.rows
          }
        ]
      },
      {
        heading: "教学评价",
        level: 1,
        intro: `评价围绕${focus}的理解和应用展开，既看课堂参与，也看任务结果是否能准确体现${evaluationTerms}。`,
        blocks: [
          {
            type: "bullet_list",
            items: [
              `过程评价：观察学习者能否围绕${conceptPair}提出问题、参与讨论并修正理解。`,
              `成果评价：检查任务输出是否准确体现${practicePair}，表达是否清楚。`,
              `反思评价：要求学习者说明${focus}判断依据、困难点和下一步改进计划。`
            ]
          }
        ]
      },
      {
        heading: "课后作业",
        level: 1,
        intro: `课后作业延伸${focus}课堂学习，让学习者在独立情境中再次运用${conceptPair}和${practicePair}。`,
        blocks: [
          {
            type: "bullet_list",
            items: [
              `围绕${topic}完成一次${focus}独立练习，明确标注${conceptPair}的判断。`,
              `用简短文字说明练习中如何处理${practicePair}。`,
              `根据课堂评价标准完成自评，并提出一个与${focus}相关的具体修改点。`
            ]
          }
        ]
      },
      {
        heading: "教学反思",
        level: 1,
        intro: `课后应复盘学习者对${focus}的掌握情况，重点分析${conceptPair}和${practicePair}哪些已经能迁移应用，哪些仍停留在记忆层面。`,
        blocks: [
          { type: "paragraph", text: `如果学习者对${evaluationTerms}的理解不稳定，后续教学应增加对比材料和分层任务；如果主要问题出现在表达或应用环节，则应加强示范、反馈和二次修改。` }
        ]
      }
    ]
  };
}

function buildReportPlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const title = makeTitleFromIntent(intent, "报告");
  const scope = scopeOrAnchors(intent);
  const scopeText = readableList(scope, focusText(intent));
  const audience = displayValue(intent.audience, "目标读者");
  const requirements = contentAnchors(intent, scope).filter((item) => !scope.includes(item));
  const requirementText = readableList(requirements, "问题原因和改进建议");
  const topic = intent.topic;
  const analysisItems = scope.length ? scope : [focusText(intent)];

  return {
    title,
    subtitle: `${scopeText}分析`,
    documentType: "report",
    sections: [
      {
        heading: "背景与现状",
        level: 1,
        intro: `本报告以“${topic}”为分析对象，面向${audience}说明${scopeText}的现状表现、影响范围和需要优先判断的问题。报告正文将结合${requirementText}给出可讨论、可落地的分析结论。`,
        blocks: [
          {
            type: "table",
            headers: ["分析维度", "现状关注点"],
            rows: analysisItems.map((item) => [item, `核对${item}的实际表现、服务触点、反馈记录和对${topic}判断的影响。`])
          }
        ]
      },
      {
        heading: "核心问题与核心发现",
        level: 1,
        intro: `核心问题从${scopeText}切入，重点不是罗列现象，而是说明每个维度为什么会影响${topic}的最终判断。`,
        blocks: [
          {
            type: "bullet_list",
            items: analysisItems.map((item) => `${item}：关注执行过程是否稳定、反馈是否及时、记录是否完整，以及这些因素如何改变${topic}的评价。`)
          },
          { type: "paragraph", text: `面向${audience}的报告表达应把${scopeText}转化为可核实的核心发现，便于后续安排责任、资源和改进节奏。` }
        ]
      },
      {
        heading: "事实与数据分析",
        level: 1,
        intro: `事实分析围绕${scopeText}建立证据链，优先使用服务记录、用户反馈、现场观察或阶段台账，而不是只给出主观判断。`,
        blocks: [
          {
            type: "table",
            headers: ["事实维度", "建议核对材料", "分析用途"],
            rows: analysisItems.map((item) => [item, `${item}相关记录、满意度反馈、异常处理和回访说明`, `用于判断${item}的问题位置、影响程度和改进优先级`])
          }
        ]
      },
      {
        heading: "原因分析",
        level: 1,
        intro: `原因分析把${scopeText}的表面问题拆到流程、资源、协同和反馈闭环中，回应${requirementText}。`,
        blocks: [
          {
            type: "bullet_list",
            items: analysisItems.map((item) => `${item}原因：检查${item}在受理、执行、记录、响应和回访中的薄弱环节，区分能力不足、协同不顺和反馈未闭环等因素。`)
          }
        ]
      },
      {
        heading: "改进建议",
        level: 1,
        intro: `建议部分面向${audience}，把原因分析转为可推进的动作，确保${scopeText}的改进能够被安排、记录和复盘。`,
        blocks: [
          {
            type: "bullet_list",
            items: analysisItems.map((item) => `${item}建议：明确牵头角色、服务标准、记录口径和回访节点，用阶段性数据比较改进前后的变化。`)
          }
        ]
      },
      {
        heading: "风险与限制",
        level: 1,
        intro: `报告结论仍受数据完整性、样本覆盖面和执行记录准确性的限制，后续推进时需要把这些限制纳入判断。`,
        blocks: [
          {
            type: "checklist",
            items: [
              `核对${scopeText}相关数据是否覆盖主要服务触点。`,
              `确认${audience}能够获得改进建议所需的责任分工和资源支持。`,
              `持续跟踪${requirementText}对应问题是否出现反复。`
            ]
          }
        ]
      },
      {
        heading: "结论",
        level: 1,
        intro: `${topic}的后续改进应以${scopeText}为主线，把问题原因、改进建议和风险控制串联起来，形成可追踪的管理动作。`,
        blocks: [{ type: "paragraph", text: `若后续补充更完整的样本数据，本报告可继续细化各维度的优先级和量化指标。` }]
      }
    ]
  };
}

function buildProposalPlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const title = makeTitleFromIntent(intent, "方案");
  const scope = scopeOrAnchors(intent);
  const scopeText = readableList(scope, focusText(intent));
  const duration = displayValue(intent.duration, "按项目周期推进");
  const audience = displayValue(intent.audience, "相关执行方");
  const topic = intent.topic;
  const workItems = scope.length ? scope : [focusText(intent)];

  return {
    title,
    subtitle: `${duration}实施安排`,
    documentType: "proposal",
    sections: [
      {
        heading: "方案目标",
        level: 1,
        intro: `本方案围绕“${topic}”制定，计划在${duration}内组织${audience}推进${scopeText}，把目标、步骤、资源、责任和验收要求写成可执行安排。`,
        blocks: [
          { type: "paragraph", text: `${scopeText}构成本次实施边界，后续执行、检查和复盘都围绕这些事项展开，保证${topic}不是口号，而是能被跟踪的具体行动。` }
        ]
      },
      {
        heading: "适用范围",
        level: 1,
        intro: `适用范围按照${scopeText}拆分，便于${audience}判断哪些事项纳入本轮执行，哪些事项需要作为后续扩展。`,
        blocks: [
          {
            type: "table",
            headers: ["范围事项", "执行边界", "协同对象"],
            rows: workItems.map((item) => [item, `围绕${item}制定任务清单、记录方式和验收口径`, audience])
          }
        ]
      },
      {
        heading: "实施步骤与执行步骤",
        level: 1,
        intro: `执行步骤按照${duration}分段推进，保证${scopeText}从准备、执行、检查到复盘都有连续安排。`,
        blocks: [
          {
            type: "numbered_list",
            items: [
              `启动准备：确认${topic}的目标、参与人员和${scopeText}的任务边界，形成执行清单。`,
              `集中推进：分别开展${workItems.map((item) => `${item}任务`).join("、")}，记录过程问题和阶段结果。`,
              `检查优化：围绕${scopeText}复核完成情况，及时调整责任分工、资源投入和执行方式。`,
              `总结固化：整理${scopeText}的经验、问题和后续安排，形成${topic}的持续推进机制。`
            ]
          }
        ]
      },
      {
        heading: "时间安排",
        level: 1,
        intro: `时间安排将${duration}拆成可检查的阶段，避免多个任务同时启动却缺少阶段成果。`,
        blocks: [
          {
            type: "timeline",
            headers: ["阶段", "时间", "重点任务"],
            rows: [
              ["启动阶段", duration === "按项目周期推进" ? "第1阶段" : `${duration}前段`, `完成${topic}目标确认、${scopeText}任务拆分和参与方动员。`],
              ["执行阶段", duration === "按项目周期推进" ? "第2阶段" : `${duration}中段`, `集中推进${workItems.map((item) => item).join("、")}，同步记录问题和阶段成果。`],
              ["验收阶段", duration === "按项目周期推进" ? "收尾阶段" : `${duration}后段`, `对照验收标准检查${scopeText}完成情况，形成复盘和改进清单。`]
            ]
          }
        ]
      },
      {
        heading: "资源配置与支持",
        level: 1,
        intro: `资源配置服务于${scopeText}的执行，重点保障人员协同、记录工具、宣传或现场材料以及问题处理渠道。`,
        blocks: [
          {
            type: "table",
            headers: ["资源类别", "配置要求", "服务任务"],
            rows: [
              ["人员", `${audience}明确牵头、协作和检查角色`, scopeText],
              ["工具", "建立过程记录、问题反馈和阶段统计表", `${topic}执行跟踪`],
              ["材料", "准备宣传、说明、检查或交付材料", workItems.slice(0, 2).join("、") || topic]
            ]
          }
        ]
      },
      {
        heading: "责任分工",
        level: 1,
        intro: `责任分工把${scopeText}落实到具体牵头和协作关系，便于执行中快速确认谁推进、谁配合、谁验收。`,
        blocks: [
          {
            type: "responsibility_matrix",
            headers: ["事项", "牵头", "协作", "交付物"],
            rows: workItems.map((item) => [item, audience, "执行协作人员", `${item}任务记录、问题清单和阶段结果`])
          }
        ]
      },
      {
        heading: "风险预案与保障",
        level: 1,
        intro: `风险预案重点处理${scopeText}执行中可能出现的资源不足、参与度下降、进度延误和验收口径不一致。`,
        blocks: [
          {
            type: "checklist",
            items: [
              `每周核对${scopeText}的任务进度和问题闭环状态。`,
              `当${audience}协同受阻时，及时调整牵头人、沟通频次和交付节奏。`,
              `对影响${topic}目标达成的风险建立记录、负责人和处理期限。`
            ]
          }
        ]
      },
      {
        heading: "验收标准与评价指标",
        level: 1,
        intro: `验收标准与评价指标直接对应${scopeText}，既看任务完成，也看过程记录和实际效果是否支撑${topic}目标。`,
        blocks: [
          {
            type: "rubric",
            headers: ["指标", "优秀", "合格"],
            rows: workItems.map((item) => [item, `${item}完成率高、记录完整、问题闭环及时`, `${item}按计划完成并保留基本过程记录`])
          }
        ]
      }
    ]
  };
}

function buildWorkSummaryPlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const title = makeTitleFromIntent(intent, "工作总结");
  const scope = scopeOrAnchors(intent, [focusText(intent)]);
  const scopeText = readableList(scope, focusText(intent));
  const audience = displayValue(intent.audience, "管理者和相关团队");
  const focus = focusText(intent);
  const nextPlan = intent.mustInclude.find((item) => /下一|下季度|下月|计划/.test(item)) || "下一步计划";
  return {
    title,
    subtitle: `${scopeText}复盘`,
    documentType: "work_summary",
    sections: [
      {
        heading: "工作概况",
        level: 1,
        intro: `${title}面向${audience}，围绕${scopeText}梳理已完成事项、成果数据、问题不足、改进措施和${nextPlan}。`,
        blocks: [
          {
            type: "table",
            headers: ["总结对象", "范围", "阅读对象"],
            rows: [[intent.topic || focus, scopeText, audience]]
          }
        ]
      },
      {
        heading: "重点完成事项",
        level: 1,
        intro: `重点完成事项按照${scopeText}展开，强调已推进的动作、形成的记录和对团队目标的支撑。`,
        blocks: [
          {
            type: "bullet_list",
            items: scope.map((item) => `${item}：完成关键对象梳理、过程跟进和阶段反馈，保留可复盘的工作记录。`)
          }
        ]
      },
      {
        heading: "成果与数据",
        level: 1,
        intro: `成果数据部分将${scopeText}转化为可汇报口径，便于${audience}判断工作投入、过程质量和结果变化。`,
        blocks: [
          {
            type: "table",
            headers: ["工作项", "成果数据口径", "管理价值"],
            rows: scope.map((item) => [item, `${item}完成量、响应时效、覆盖对象和异常闭环情况`, `用于判断${item}对${intent.topic}的贡献和改进空间`])
          }
        ]
      },
      {
        heading: "问题与不足",
        level: 1,
        intro: `问题不足不是否定已有工作，而是指出${scopeText}中影响效率、体验或结果稳定性的环节。`,
        blocks: [
          {
            type: "bullet_list",
            items: scope.map((item) => `${item}仍需加强数据沉淀、跨角色协同和过程提醒，避免推进依赖个人经验。`)
          }
        ]
      },
      {
        heading: "改进措施",
        level: 1,
        intro: `改进措施围绕${scopeText}建立更清晰的记录、复盘和协同机制，使问题不足能够转化为可执行动作。`,
        blocks: [
          {
            type: "checklist",
            items: scope.map((item) => `为${item}建立固定台账、周度检查点和异常升级规则。`)
          }
        ]
      },
      {
        heading: "下一步计划",
        level: 1,
        intro: `${nextPlan}将继续围绕${scopeText}推进，并把改进措施纳入日常管理节奏。`,
        blocks: [
          {
            type: "timeline",
            headers: ["阶段", "重点", "输出"],
            rows: [
              ["启动", `确认${scopeText}的优先级和责任人`, "下阶段计划表"],
              ["推进", `按周跟踪${scope.map((item) => `${item}进展`).join("、")}`, "过程台账和问题清单"],
              ["复盘", `评估改进措施对${intent.topic}的实际效果`, "复盘结论和后续建议"]
            ]
          }
        ]
      }
    ]
  };
}

function buildMeetingMinutesPlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const title = makeTitleFromIntent(intent, "会议纪要");
  const agenda = scopeOrAnchors(intent, ["议题"]);
  const agendaText = readableList(agenda, focusText(intent));
  const audience = displayValue(intent.audience, "参会人员");
  const meetingTime = displayValue(intent.duration, "会议时间按实际记录填写");

  return {
    title,
    subtitle: meetingTime,
    documentType: "meeting_minutes",
    sections: [
      {
        heading: "会议基本信息",
        level: 1,
        intro: `本纪要记录“${intent.topic}”会议的基本信息、讨论要点、决议事项和后续待办，便于${audience}统一行动。`,
        blocks: [
          {
            type: "table",
            headers: ["项目", "内容"],
            rows: [
              ["会议名称", intent.topic],
              ["会议时间", meetingTime],
              ["参会对象", audience],
              ["会议议题", agendaText]
            ]
          }
        ]
      },
      {
        heading: "议题",
        level: 1,
        intro: `会议议题围绕${agendaText}展开，每个议题都需要形成明确讨论结论或后续跟进动作。`,
        blocks: [{ type: "bullet_list", items: agenda.map((item) => `${item}：明确背景、当前进展、需要会议确认的问题。`) }]
      },
      {
        heading: "讨论要点",
        level: 1,
        intro: `讨论要点按议题归纳，保留分歧、风险和需要补充的信息，避免纪要只写结论不写依据。`,
        blocks: [
          {
            type: "table",
            headers: ["议题", "讨论要点", "后续关注"],
            rows: agenda.map((item) => [item, `围绕${item}的进度、影响范围、资源需求和风险进行讨论。`, `补齐${item}相关数据、流程或用户反馈。`])
          }
        ]
      },
      {
        heading: "决议事项",
        level: 1,
        intro: `决议事项把${agendaText}对应的会议共识写成明确动作，避免会后理解不一致。`,
        blocks: [
          {
            type: "numbered_list",
            items: agenda.map((item) => `${item}：按会议确认方向推进，并在下一次同步中汇报阶段结果。`)
          }
        ]
      },
      {
        heading: "待办任务",
        level: 1,
        intro: `待办任务需要和责任人与截止时间关联，确保${agendaText}不会停留在讨论层面。`,
        blocks: [
          {
            type: "checklist",
            items: agenda.map((item) => `完成${item}的执行记录、风险确认和结果反馈。`)
          }
        ]
      },
      {
        heading: "责任人与截止时间",
        level: 1,
        intro: `责任人与截止时间用于跟踪会议后的执行闭环，责任人、协作方和时间节点应在会后及时确认。`,
        blocks: [
          {
            type: "responsibility_matrix",
            headers: ["待办任务", "责任人", "截止时间", "备注"],
            rows: agenda.map((item) => [`推进${item}`, "会议指定负责人", "按会议约定时间", `与${audience}同步进展`])
          }
        ]
      }
    ]
  };
}

function buildResearchSummaryPlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const title = makeTitleFromIntent(intent, "研究综述");
  const focus = focusText(intent);
  const anchors = scopeOrAnchors(intent, [focus]);
  const anchorLine = readableList(anchors, focus);
  return {
    title,
    subtitle: anchorLine,
    documentType: "research_summary",
    sections: [
      { heading: "研究背景", level: 1, intro: `本综述围绕${intent.topic}展开，先交代${focus}的研究语境和实际问题。`, blocks: [{ type: "paragraph", text: `${anchorLine}构成综述的主要线索，后续分析将围绕这些线索展开。` }] },
      { heading: "研究现状", level: 1, intro: `研究现状部分梳理${anchorLine}的主要观点、常用方法和争议焦点。`, blocks: [{ type: "table", headers: ["方向", "关注点"], rows: anchors.map((item) => [item, `整理${item}的概念、方法和典型结论。`]) }] },
      { heading: "核心观点", level: 1, intro: `核心观点部分把已有材料归纳为可比较的判断，而不是摘抄资料。`, blocks: [{ type: "bullet_list", items: anchors.map((item) => `${item}：比较不同观点的适用条件、证据基础和局限。`) }] },
      { heading: "启示与建议", level: 1, intro: `${intent.topic}的后续研究或实践可从${anchorLine}中提炼问题、方法和评价指标。`, blocks: [{ type: "paragraph", text: `综述结论应服务于后续选题、方案设计或报告写作，避免停留在材料堆叠。` }] }
    ]
  };
}

function buildCoursePlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const proposal = buildProposalPlanFromIntent({ ...intent, documentType: "proposal" });
  return {
    ...proposal,
    title: makeTitleFromIntent(intent, "课程方案"),
    subtitle: focusText(intent),
    documentType: "course_plan",
    sections: [
      { heading: "课程定位", level: 1, intro: `${intent.topic}课程方案面向${displayValue(intent.audience, "目标学习者")}，围绕${focusText(intent)}明确课程价值、学习边界和实施方式。`, blocks: [{ type: "paragraph", text: `课程内容应与${anchorText(intent)}保持一致，帮助学习者获得可迁移的知识和任务能力。` }] },
      { heading: "课程目标", level: 1, intro: `课程目标把${anchorText(intent)}转化为知识理解、实践能力和学习成果。`, blocks: [{ type: "bullet_list", items: contentAnchors(intent, [focusText(intent)]).map((item) => `围绕${item}完成学习、练习和评价。`) }] },
      ...proposal.sections.filter((section) => /适用范围|实施步骤|时间安排|资源配置|验收标准/.test(section.heading))
    ]
  };
}

function buildTrainingPlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const plan = buildProposalPlanFromIntent({ ...intent, documentType: "proposal" });
  const duration = displayValue(intent.duration, /三天|3天|三日|3日/.test(`${intent.duration || ""} ${intent.mustInclude.join(" ")}`) ? "三天" : "按培训周期推进");
  const focus = focusText(intent);
  const anchors = scopeOrAnchors(intent, [focus]);
  const requiresThreeDayFlow = /三天|3天|三日|3日/.test(`${intent.duration || ""} ${intent.mustInclude.join(" ")} ${intent.requirements.join(" ")}`);
  const normalizedSections = plan.sections
    .filter((section) => /时间安排|责任分工|验收标准|评价指标|风险/.test(section.heading))
    .filter((section) => !(requiresThreeDayFlow && /时间安排/.test(section.heading)))
    .map((section) => {
      if (/时间安排/.test(section.heading)) {
        return {
          ...section,
          heading: requiresThreeDayFlow ? "三天培训流程与时间安排" : "培训流程与时间安排",
          intro: requiresThreeDayFlow
            ? `三天培训流程按“认知导入、岗位实践、考核复盘”推进，确保${intent.topic}的新员工培训有明确节奏和阶段产出。`
            : section.intro
        };
      }
      if (/验收标准|评价指标/.test(section.heading)) {
        return {
          ...section,
          heading: "考核方式与评价标准",
          intro: `考核方式围绕${focus}设置，兼顾知识理解、岗位实践、过程记录和复盘改进，避免只看签到不看学习成效。`
        };
      }
      if (/风险/.test(section.heading)) {
        return {
          ...section,
          heading: "风险预案",
          intro: `风险预案聚焦${intent.topic}培训中可能出现的时间冲突、导师缺位、学习吸收不足和考核反馈滞后。`
        };
      }
      return section;
    });
  return {
    ...plan,
    title: makeTitleFromIntent(intent, "培训方案"),
    documentType: "training_plan",
    sections: [
      {
        heading: "培训目标",
        level: 1,
        intro: `培训方案面向${displayValue(intent.audience, "参训对象")}，围绕${focus}提升制度理解、岗位操作、协作沟通和复盘改进能力。`,
        blocks: [{ type: "paragraph", text: `培训成果应能支撑${intent.topic}在真实岗位场景中的应用，学员完成后能够说明关键流程、完成基础任务并接受考核反馈。` }]
      },
      {
        heading: "培训内容",
        level: 1,
        intro: `培训内容按${anchorText(intent)}组织，兼顾讲解、演示、练习、反馈和成果提交。`,
        blocks: [{ type: "table", headers: ["模块", "训练重点"], rows: anchors.map((item) => [item, `围绕${item}设置讲解、演示、任务练习和现场答疑。`]) }]
      },
      ...(requiresThreeDayFlow
        ? [
            {
              heading: "三天培训流程与时间安排",
              level: 1 as const,
              intro: `三天流程把${intent.topic}拆成入职认知、岗位实践和考核复盘三个阶段，确保每天都有明确产出。`,
              blocks: [
                {
                  type: "timeline" as const,
                  headers: ["时间", "培训安排", "产出"],
                  rows: [
                    ["第一天", "公司制度、组织文化、办公流程和入职规范说明", "入职学习记录与问题清单"],
                    ["第二天", "岗位流程演示、导师带教、场景练习和阶段反馈", "岗位练习成果与导师反馈"],
                    ["第三天", "综合演练、答疑复盘、考核确认和改进建议", "考核结果、补训建议与转正前跟进清单"]
                  ]
                }
              ]
            }
          ]
        : []),
      ...normalizedSections
    ]
  };
}

function buildBusinessPlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const proposal = buildProposalPlanFromIntent({ ...intent, documentType: "proposal" });
  return {
    ...proposal,
    title: makeTitleFromIntent(intent, "商业计划书"),
    documentType: "business_plan",
    sections: [
      { heading: "项目概述", level: 1, intro: `本商业计划书围绕${intent.topic}说明目标市场、价值主张、执行路径和风险控制。`, blocks: [{ type: "paragraph", text: `${anchorText(intent)}是计划书中需要重点验证和推进的内容。` }] },
      { heading: "市场与用户", level: 1, intro: `市场与用户部分分析${focusText(intent)}对应的需求、痛点和使用场景。`, blocks: [{ type: "table", headers: ["维度", "分析重点"], rows: scopeOrAnchors(intent, [focusText(intent)]).map((item) => [item, `判断${item}的需求强度、竞争环境和转化机会。`]) }] },
      { heading: "产品与服务", level: 1, intro: `产品与服务要把${intent.topic}的价值写成用户能理解、团队能执行的交付内容。`, blocks: [{ type: "bullet_list", items: contentAnchors(intent, [focusText(intent)]).map((item) => `围绕${item}明确功能、体验和交付边界。`) }] },
      ...proposal.sections.filter((section) => /实施步骤|资源配置|责任分工|风险|验收标准/.test(section.heading))
    ]
  };
}

function buildNoticePlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const title = makeTitleFromIntent(intent, "通知");
  const scope = scopeOrAnchors(intent, [focusText(intent)]);
  return {
    title,
    subtitle: displayValue(intent.duration, "事项安排"),
    documentType: "notice",
    sections: [
      { heading: "通知事项", level: 1, intro: `现就${intent.topic}相关事项通知如下，重点涉及${readableList(scope, focusText(intent))}。`, blocks: [{ type: "paragraph", text: `请相关对象按通知要求做好准备、执行和反馈。` }] },
      { heading: "适用对象", level: 1, intro: `本通知面向${displayValue(intent.audience, "相关人员或部门")}，执行时应确认职责范围和反馈渠道。`, blocks: [{ type: "bullet_list", items: scope.map((item) => `${item}相关人员需按要求完成对应事项。`) }] },
      { heading: "执行要求", level: 1, intro: `执行要求围绕${anchorText(intent)}展开，重点保证时间、材料和结果反馈清楚。`, blocks: [{ type: "checklist", items: scope.map((item) => `完成${item}并反馈执行情况。`) }] }
    ]
  };
}

function buildContractPlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const title = makeTitleFromIntent(intent, "合同");
  const scope = scopeOrAnchors(intent, [focusText(intent)]);
  return {
    title,
    subtitle: anchorText(intent),
    documentType: "contract",
    sections: [
      { heading: "合同目的", level: 1, intro: `本合同围绕${intent.topic}明确合作目标、权责边界和履约要求。`, blocks: [{ type: "paragraph", text: `${readableList(scope, focusText(intent))}是合同条款需要覆盖的重点内容。` }] },
      { heading: "主要条款", level: 1, intro: `主要条款应覆盖标的、交付、付款、验收、保密和违约处理等内容。`, blocks: [{ type: "table", headers: ["条款", "要点"], rows: scope.map((item) => [item, `明确${item}的责任、标准、时间和验收方式。`]) }] },
      { heading: "履约与风险", level: 1, intro: `履约管理应重点关注进度、质量、资料交付和争议处理。`, blocks: [{ type: "checklist", items: [`确认${intent.topic}的交付标准。`, "明确双方责任人与沟通机制。", "保留履约记录和验收证据。"] }] }
    ]
  };
}

function buildGeneralFormalPlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  const title = makeTitleFromIntent(intent, "文档");
  const scope = scopeOrAnchors(intent, [focusText(intent)]);
  const scopeText = readableList(scope, focusText(intent));
  return {
    title,
    subtitle: intent.purpose || scopeText,
    documentType: "general",
    sections: [
      { heading: "文档概述", level: 1, intro: `本文件围绕${intent.topic}整理正式内容，适合内部提交、讨论或后续修改。`, blocks: [{ type: "paragraph", text: `重点聚焦${scopeText}，并把目的、对象和约束写清楚。` }] },
      { heading: "主要内容", level: 1, intro: `主要内容按${scopeText}展开，避免空泛套话。`, blocks: [{ type: "bullet_list", items: scope.map((item) => `${item}：补齐背景、做法和结果说明。`) }] },
      { heading: "使用建议", level: 1, intro: `如需继续完善，可按用途补充更具体的时间、责任、数据或案例。`, blocks: [{ type: "table", headers: ["项目", "建议"], rows: [["适用场景", "内部汇报、讨论或提交"], ["后续补充", "根据实际用途再细化数据和案例"]] }] }
    ]
  };
}

function buildSummaryPlanFromIntent(intent: WordGenerationIntent): WordDocumentPlan {
  return buildWorkSummaryPlanFromIntent({ ...intent, documentType: "work_summary" });
}

export function buildWordDocumentPlanFromIntent(intent: WordGenerationIntent, template: DocumentTemplate): WordDocumentPlan {
  if (intent.documentType === "lesson_plan" || template === "lesson_plan") return buildLessonPlanFromIntent(intent);
  if (intent.documentType === "course_plan") return buildCoursePlanFromIntent(intent);
  if (intent.documentType === "training_plan") return buildTrainingPlanFromIntent(intent);
  if (intent.documentType === "business_plan") return buildBusinessPlanFromIntent(intent);
  if (intent.documentType === "work_summary") return buildWorkSummaryPlanFromIntent(intent);
  if (intent.documentType === "research_summary") return buildResearchSummaryPlanFromIntent(intent);
  if (intent.documentType === "meeting_minutes" || template === "meeting_minutes") return buildMeetingMinutesPlanFromIntent(intent);
  if (intent.documentType === "notice") return buildNoticePlanFromIntent(intent);
  if (intent.documentType === "contract") return buildContractPlanFromIntent(intent);
  if (intent.documentType === "proposal" || template === "proposal") return buildProposalPlanFromIntent(intent);
  if (intent.documentType === "summary") return buildSummaryPlanFromIntent(intent);
  if (intent.documentType === "general" && template === "general") return buildGeneralFormalPlanFromIntent(intent);
  return buildReportPlanFromIntent(intent);
}

function looksLikeRawPrompt(markdown: string, blocks: MarkdownBlock[]) {
  const hasHeading = blocks.some((block) => block.type === "heading");
  if (hasHeading) return false;
  const compact = markdown.replace(/\s+/g, "");
  return compact.length > 0 && compact.length < 500;
}

function buildGenericPlan(markdown: string, title: string, template: DocumentTemplate, intent?: WordGenerationIntent): WordDocumentPlan {
  const blocks = parseMarkdown(markdown);
  const resolvedIntent = intent || extractWordGenerationIntent(uniqueIntentSource(title, markdown));
  if (isUsableWordIntent(resolvedIntent) && looksLikeRawPrompt(markdown, blocks)) {
    return buildWordDocumentPlanFromIntent(resolvedIntent, template);
  }

  const planTitle = cleanTitlePart(inferTitle(title, blocks)) || makeTitleFromIntent(resolvedIntent, template === "proposal" ? "方案" : template === "report" ? "报告" : "文档");
  const sections: WordSection[] = [];
  let current: WordSection | null = null;

  const pushCurrent = () => {
    if (!current) return;
    sections.push(ensureSectionNarrative(current, planTitle));
  };

  for (const block of blocks) {
    if (block.type === "heading") {
      if (block.level === 1 && cleanText(block.text) === planTitle && !current && !sections.length) continue;
      pushCurrent();
      current = { heading: stripHeadingNumber(block.text), level: Math.min(Math.max(block.level, 1), 4) as 1 | 2 | 3 | 4, blocks: [] };
      continue;
    }

    if (!current) current = { heading: "概述", level: 1, blocks: [] };

    if (block.type === "paragraph") {
      const text = cleanText(block.text, 520);
      if (!text) continue;
      if (!current.intro) current.intro = text;
      else current.blocks.push({ type: "paragraph", text });
    } else if (block.type === "list") {
      current.blocks.push(...listToBlocks(current.heading, block.ordered, block.items));
    } else if (block.type === "table") {
      const table = tableBlock(block.rows);
      if (table) current.blocks.push(lessonProcessTableFromMarkdown(table, current.heading));
    } else if (block.type === "code") {
      const text = cleanText(block.text, 520);
      if (text) current.blocks.push({ type: "callout", title: "补充说明", text });
    }
  }
  pushCurrent();

  const sourceSummary = textFromBlocks(blocks);
  const finalSections = sections.length
    ? sections
    : [
        {
          heading: "概述",
          level: 1 as const,
          intro: sourceSummary || `${planTitle}围绕用户需求整理为正式文档，内容按背景、要点和后续行动展开。`,
          blocks: []
        }
      ];

  return {
    title: planTitle,
    subtitle: sourceSummary.length > 28 ? sourceSummary.slice(0, 90) : undefined,
    documentType: documentTypeFromTemplate(template),
    sections: finalSections
  };
}

function buildLessonPlan(markdown: string, title: string, intent?: WordGenerationIntent): WordDocumentPlan {
  const blocks = parseMarkdown(markdown);
  const source = textFromBlocks(blocks);
  if (!intent && blocks.some((block) => block.type === "heading")) {
    return buildGenericPlan(markdown, title, "lesson_plan");
  }
  return buildLessonPlanFromIntent(intent || extractWordGenerationIntent(uniqueIntentSource(title, source || markdown)));
}

export function buildWordDocumentPlan({
  markdown,
  title,
  template,
  intent
}: {
  markdown: string;
  title: string;
  template: DocumentTemplate;
  prompt?: string;
  intent?: WordGenerationIntent;
}): WordDocumentPlan {
  const modelPlan = parseWordDocumentPlanJson(markdown);
  if (modelPlan) {
    return {
      ...modelPlan,
      documentType: modelPlan.documentType || documentTypeFromIntent(intent || extractWordGenerationIntent(uniqueIntentSource(title, markdown)), template)
    };
  }
  const resolvedIntent = intent || extractWordGenerationIntent(uniqueIntentSource(title, markdown));
  if (template === "lesson_plan") return buildLessonPlan(markdown, title, intent);
  return buildGenericPlan(markdown, title, template, resolvedIntent);
}
