import {
  buildWordDocumentPlanFromIntent,
  isUsableWordIntent,
  type WordBlock,
  type WordDocumentPlan,
  type WordGenerationIntent,
  type WordSection
} from "./plan";

export type WordQualityIssueCode =
  | "platform_signature"
  | "too_many_numbered_lists"
  | "heading_without_body"
  | "missing_structure_mix"
  | "lesson_plan_missing_required_section"
  | "missing_intent_keyword"
  | "title_uses_prompt"
  | "template_title"
  | "template_text"
  | "prompt_echo"
  | "repeated_phrase"
  | "weak_intent_grounding"
  | "section_similarity"
  | "generic_lesson_process"
  | "document_type_mismatch"
  | "insufficient_intent"
  | "missing_required_section"
  | "empty_structured_block"
  | "non_actionable_content"
  | "placeholder_content"
  | "unsupported_specific_data";

export type WordQualityIssue = {
  code: WordQualityIssueCode;
  message: string;
  severity: "low" | "medium" | "high";
};

export type WordQualityReport = {
  keywordCoverage: WordIntentKeywordCoverage;
  score: number;
  issues: WordQualityIssue[];
  shouldRepair: boolean;
};

export type WordIntentKeywordCoverage = {
  coverageScore: number;
  coreMatched: boolean;
  matchedKeywords: string[];
  missingCoreKeywords: string[];
  missingKeywords: string[];
  totalKeywords: number;
};

const REQUIRED_LESSON_SECTIONS = ["基本信息", "设计思路", "教学目标", "教学过程", "教学评价"];
const REQUIRED_SECTIONS_BY_TYPE: Partial<Record<NonNullable<WordDocumentPlan["documentType"]>, string[]>> = {
  proposal: ["目标", "适用范围", "步骤", "时间安排", "责任分工", "风险", "验收"],
  business_plan: ["项目概述", "市场", "产品", "实施", "风险"],
  work_summary: ["工作概况", "重点完成事项", "成果", "问题", "改进", "下一步计划"],
  meeting_minutes: ["会议基本信息", "议题", "讨论要点", "决议", "待办", "责任人"],
  training_plan: ["培训目标", "培训内容", "时间安排", "责任分工", "考核"]
};
const TEMPLATE_SMELLS = [
  "结构清晰、便于继续修改和交付",
  "补充具体数据、案例或附件内容后",
  "如需更强格式",
  "待补充",
  "文档主题",
  "交付重点",
  "本部分用于补充",
  "这个部分用于",
  "请根据班级基础和课程目标进一步补充",
  "用户指定",
  "上述范围",
  "上述分析范围",
  "相关要求",
  "流程衔接",
  "反馈处理",
  "责任明确",
  "动作可查",
  "周期复盘"
];

function cleanText(value: unknown, maxLength = 420) {
  return String(value || "")
    .replace(/\s+/g, " ")
    .replace(/(?:Generated by NexusAI|由\s*NexusAI\s*生成|NexusAI\s*智能文档模块|NexusAI)/gi, "")
    .trim()
    .slice(0, maxLength);
}

function isTemplateLabelTitle(value: string) {
  return /^(?:Lesson Plan|Proposal|Document|Meeting Minutes|DocTemplate|Research Report|Formal Document)$/i.test(cleanText(value, 80));
}

function isTableLikeBlock(block: WordBlock) {
  return block.type === "table" || block.type === "rubric" || block.type === "timeline" || block.type === "responsibility_matrix";
}

function blockTexts(block: WordBlock) {
  if (block.type === "paragraph") return [block.text];
  if (block.type === "bullet_list" || block.type === "numbered_list" || block.type === "checklist") return block.items;
  if (isTableLikeBlock(block)) return [block.headers, ...block.rows].flat();
  if (block.type === "callout") return [block.title, block.text];
  return [];
}

function sectionHasBody(section: WordSection) {
  return Boolean(section.intro) || section.blocks.some((block) => block.type === "paragraph" || isTableLikeBlock(block) || block.type === "callout" || block.type === "checklist");
}

function sectionStartsWithUnsupportedList(section: WordSection) {
  if (section.intro) return false;
  const firstBlock = section.blocks[0];
  return firstBlock?.type === "bullet_list" || firstBlock?.type === "numbered_list" || firstBlock?.type === "checklist";
}

const PLACEHOLDER_PATTERNS = [
  /相关内容/g,
  /相关负责人/g,
  /相关参与人员/g,
  /主责部门或负责人/g,
  /对应牵头人/g,
  /待补充/g,
  /待定/g,
  /按实际填写/g,
  /视情况/g,
  /若干/g
];

function countPlaceholderTerms(text: string) {
  return PLACEHOLDER_PATTERNS.reduce((total, pattern) => total + (text.match(pattern) || []).length, 0);
}

function countUnsupportedSpecificData(text: string) {
  const matches = text.match(/(?:\d+(?:\.\d+)?%|\d+(?:\.\d+)?万元|\d+(?:\.\d+)?人|\d+(?:\.\d+)?家|\d+(?:\.\d+)?次)/g) || [];
  return matches.filter((match) => {
    const index = text.indexOf(match);
    const context = text.slice(Math.max(0, index - 16), Math.min(text.length, index + match.length + 16));
    return !/建议|示例|参考|可按实际调整|按实际|约|左右|不少于|不低于|不超过|以内|以上|第/.test(context);
  }).length;
}

function hasBlockType(plan: WordDocumentPlan, type: WordBlock["type"]) {
  return plan.sections.some((section) => section.blocks.some((block) => block.type === type));
}

function hasTableLikeBlock(plan: WordDocumentPlan) {
  return plan.sections.some((section) => section.blocks.some((block) => isTableLikeBlock(block)));
}

function countNumberedLists(plan: WordDocumentPlan) {
  return plan.sections.reduce((total, section) => total + section.blocks.filter((block) => block.type === "numbered_list").length, 0);
}

function countUnsupportedNumberedLists(plan: WordDocumentPlan) {
  return plan.sections.reduce((total, section) => {
    if (/过程|流程|步骤|清单|标准|评价|安排|计划|待办|任务|决议/.test(section.heading)) return total;
    return (
      total +
      section.blocks.filter((block) => {
        if (block.type !== "numbered_list") return false;
        const actionItems = block.items.filter((item) => /^(核对|确认|输出|建立|梳理|明确|跟踪|复核|安排|设置|更新|汇总|记录|检查|完善|制定|拆分|沉淀|补齐|统一|优化|设计|比较|增加|推进|评估|归档|校准)/.test(cleanText(item, 40)));
        return actionItems.length < Math.ceil(block.items.length * 0.6);
      }).length
    );
  }, 0);
}

function fallbackIntro(section: WordSection, title: string) {
  return `${section.heading}部分对“${title}”的相关内容进行说明，先交代核心含义和使用场景，再展开具体要求。`;
}

function textFromPlan(plan: WordDocumentPlan) {
  return [
    plan.title,
    plan.subtitle,
    ...plan.sections.flatMap((section) => [
      section.heading,
      section.intro,
      ...section.blocks.flatMap(blockTexts)
    ])
  ]
    .filter(Boolean)
    .join(" ");
}

function textFromSection(section: WordSection) {
  return [
    section.heading,
    section.intro,
    ...section.blocks.flatMap(blockTexts)
  ]
    .filter(Boolean)
    .join(" ");
}

function compact(value: string) {
  return value.replace(/\s+/g, "").replace(/[，。；、,.!?！？:："'“”《》]/g, "").toLowerCase();
}

function splitIntentItems(value?: string) {
  return cleanText(value, 160)
    .split(/[、,，/；;]|\s*(?:和|与)\s*/u)
    .map((item) => cleanText(item, 80))
    .filter((item) => item.length >= 2);
}

function isDeliveryOrStyleRequirement(value?: string) {
  const text = cleanText(value, 80);
  if (!text) return false;
  return /^(?:正式|专业|完整|规范|严谨|可直接交付|直接交付|可直接使用|直接使用|可修改|内容正式|条理清晰|结构清晰|二十个以上专题|表格|步骤清单|清单|列表)$/.test(text);
}

function isSyntheticChapterRequirement(value?: string) {
  return /^突出第[一二三四五六七八九十百千万\d]+章节?$/.test(cleanText(value, 80));
}

function uniqueValues(values: string[]) {
  const seen = new Set<string>();
  const result: string[] = [];
  for (const value of values.map((item) => cleanText(item, 80)).filter(Boolean)) {
    const key = compact(value);
    if (!key || seen.has(key)) continue;
    seen.add(key);
    result.push(value);
  }
  return result;
}

function significantIntentKeywords(intent?: WordGenerationIntent) {
  if (!intent) return [];
  return uniqueValues([
    intent.topic,
    intent.purpose,
    intent.chapter,
    intent.chapterTitle,
    intent.scope,
    intent.duration,
    intent.lengthRequirement,
    intent.audience,
    ...intent.mustInclude,
    ...intent.requirements,
    ...intent.keywords
  ].filter((value): value is string => Boolean(value)))
    .filter((value) => value.length >= 2 && !isDeliveryOrStyleRequirement(value) && !isSyntheticChapterRequirement(value) && !/^(教案|报告|方案|总结|文档|文件)$/.test(value));
}

function isExplicitMustIncludeKeyword(intent: WordGenerationIntent | undefined, keyword: string) {
  if (!intent) return false;
  const key = compact(keyword);
  return intent.mustInclude.some((item) => {
    const itemKey = compact(item);
    if (itemKey === key || itemKey.includes(key) || key.includes(itemKey)) return true;
    return splitIntentItems(item).some((part) => compact(part) === key);
  });
}

const KEYWORD_SYNONYM_GROUPS = [
  ["问题原因", "原因分析", "成因分析", "问题成因"],
  ["改进建议", "优化建议", "建议方案", "改善措施"],
  ["实施步骤", "执行步骤", "推进步骤", "实施路径"],
  ["评价指标", "评价标准", "验收标准", "考核指标"],
  ["成果数据", "成果与数据", "关键成果", "量化成果", "数据成果"],
  ["问题不足", "问题与不足", "不足问题", "短板不足"],
  ["课后任务", "课后作业", "延伸任务"],
  ["教学评价", "评价方式", "评价标准"],
  ["授课对象", "学习者", "学生", "参训对象"],
  ["课时", "学时", "时长"],
  ["会议时间", "时间"],
  ["责任人", "牵头人", "负责方"],
  ["截止时间", "完成时间", "时间节点"]
];

function chineseOrdinalToArabic(value: string) {
  if (/^\d+$/.test(value)) return value;
  const map: Record<string, number> = {
    一: 1,
    二: 2,
    两: 2,
    三: 3,
    四: 4,
    五: 5,
    六: 6,
    七: 7,
    八: 8,
    九: 9,
    十: 10
  };
  if (map[value]) return String(map[value]);
  const tenMatch = value.match(/^十([一二三四五六七八九])$/);
  if (tenMatch) return String(10 + map[tenMatch[1]]);
  const compoundMatch = value.match(/^([一二三四五六七八九])十([一二三四五六七八九])?$/);
  if (compoundMatch) return String(map[compoundMatch[1]] * 10 + (compoundMatch[2] ? map[compoundMatch[2]] : 0));
  return "";
}

function chapterKeywordAliases(keyword: string) {
  const match = cleanText(keyword, 40).match(/^第([一二两三四五六七八九十百千万\d]+)(章节|章|节)$/);
  if (!match) return [];
  const ordinal = match[1];
  const arabic = chineseOrdinalToArabic(ordinal);
  return uniqueValues([
    `第${ordinal}章节`,
    `第${ordinal}章`,
    `第${ordinal}节`,
    arabic ? `第${arabic}章节` : "",
    arabic ? `第${arabic}章` : "",
    arabic ? `第${arabic}节` : "",
    `${ordinal}章节`,
    `${ordinal}章`,
    `${ordinal}节`
  ].filter(Boolean));
}

function keywordAliases(keyword: string) {
  const key = compact(keyword);
  const group = KEYWORD_SYNONYM_GROUPS.find((items) => items.some((item) => key.includes(compact(item)) || compact(item).includes(key)));
  return uniqueValues([keyword, ...chapterKeywordAliases(keyword), ...(group || [])]);
}

function keywordMatches(compactText: string, keyword: string) {
  const key = compact(keyword);
  if (!key) return false;
  for (const alias of keywordAliases(keyword)) {
    const aliasKey = compact(alias);
    if (aliasKey && compactText.includes(aliasKey)) return true;
  }
  const parts = splitIntentItems(keyword).map(compact).filter((item) => item.length >= 2);
  if (parts.length >= 2) {
    const hits = parts.filter((part) => compactText.includes(part)).length;
    return hits >= Math.ceil(parts.length * 0.6);
  }
  if (key.length >= 8) {
    const grams = new Set<string>();
    for (let index = 0; index <= key.length - 3; index += 2) {
      grams.add(key.slice(index, index + 3));
    }
    const hits = [...grams].filter((gram) => compactText.includes(gram)).length;
    return grams.size > 0 && hits / grams.size >= 0.72;
  }
  return false;
}

function coreIntentKeywords(intent?: WordGenerationIntent) {
  if (!intent) return [];
  return uniqueValues([
    intent.topic,
    intent.chapter,
    intent.chapterTitle,
    intent.scope,
    intent.duration,
    intent.audience
  ].filter((value): value is string => Boolean(value)))
    .filter((value) => value.length >= 2 && !isDeliveryOrStyleRequirement(value) && !isSyntheticChapterRequirement(value));
}

export function getWordIntentKeywordCoverage(plan: WordDocumentPlan, intent?: WordGenerationIntent): WordIntentKeywordCoverage {
  const keywords = significantIntentKeywords(intent);
  const coreKeywords = coreIntentKeywords(intent);
  const compactText = compact(textFromPlan(plan));
  const matchedKeywords: string[] = [];
  const missingKeywords: string[] = [];
  const missingCoreKeywords: string[] = [];

  for (const keyword of keywords) {
    if (keywordMatches(compactText, keyword)) {
      matchedKeywords.push(keyword);
    } else {
      missingKeywords.push(keyword);
      if (coreKeywords.some((core) => compact(core) === compact(keyword))) missingCoreKeywords.push(keyword);
    }
  }

  const coreMatched = coreKeywords.length === 0 || coreKeywords.some((keyword) => keywordMatches(compactText, keyword));
  const coverageScore = keywords.length ? Math.round((matchedKeywords.length / keywords.length) * 100) : 100;
  return {
    coverageScore,
    coreMatched,
    matchedKeywords,
    missingCoreKeywords,
    missingKeywords,
    totalKeywords: keywords.length
  };
}

function groundingIntentKeywords(intent?: WordGenerationIntent) {
  if (!intent) return [];
  const identity = new Set([
    intent.topic,
    intent.chapter,
    intent.duration,
    intent.audience,
    intent.lengthRequirement
  ].map((item) => compact(cleanText(item, 80))).filter(Boolean));
  return uniqueValues([
    intent.purpose,
    intent.chapterTitle,
    ...splitIntentItems(intent.scope),
    ...intent.mustInclude.flatMap(splitIntentItems),
    ...intent.requirements.flatMap(splitIntentItems),
    ...intent.keywords.flatMap(splitIntentItems)
  ].filter((value): value is string => Boolean(value))).filter((value) => {
    const key = compact(value);
    return key && !identity.has(key) && !isDeliveryOrStyleRequirement(value) && !isSyntheticChapterRequirement(value) && !/^(教案|报告|方案|总结|文档|文件|课时|页数|表格|清单|列表|步骤清单)$/.test(value);
  });
}

function countRepeatedPhrases(text: string) {
  const phrases = text.match(/[\u4e00-\u9fa5]{4,12}/g) || [];
  const counts = new Map<string, number>();
  for (const phrase of phrases) counts.set(phrase, (counts.get(phrase) || 0) + 1);
  const allowedRepeated = [
    "教学过程",
    "评价标准",
    "实施步骤",
    "年度运营复盘",
    "复盘结论",
    "责任分工",
    "基础数据",
    "后续动作",
    "当前情况",
    "风险影响",
    "运营复盘",
    "基础数据",
    "责任追踪",
    "管理层",
    "跨团队",
    "后续优先级",
    "复盘判断"
  ];
  const threshold = Math.max(8, Math.ceil(compact(text).length / 1500));
  return [...counts.entries()].filter(
    ([phrase, count]) =>
      count >= threshold &&
      !allowedRepeated.some((allowed) => phrase.includes(allowed) || allowed.includes(phrase)) &&
      !/(责任|复盘|数据|风险|后续|运营|专题|协同|结论|动作|记录|管理|资源|团队|判断|影响|规律|目标|评价|课程|教学|任务|练习|活动)/.test(phrase)
  );
}

function ngramSimilarity(leftValue: string, rightValue: string) {
  const grams = (value: string) => {
    const compactText = compact(value);
    const result = new Set<string>();
    for (let index = 0; index <= compactText.length - 10; index += 1) {
      result.add(compactText.slice(index, index + 10));
    }
    return result;
  };
  const left = grams(leftValue);
  const right = grams(rightValue);
  if (!left.size || !right.size) return 0;
  let overlap = 0;
  for (const item of left) {
    if (right.has(item)) overlap += 1;
  }
  return overlap / Math.min(left.size, right.size);
}

function findHighlySimilarSections(plan: WordDocumentPlan) {
  const sections = contentSectionsForGrounding(plan)
    .map((section) => ({ heading: section.heading, text: textFromSection(section) }))
    .filter((section) => compact(section.text).length > 80);
  const pairs: Array<{ left: string; right: string; similarity: number }> = [];
  for (let leftIndex = 0; leftIndex < sections.length; leftIndex += 1) {
    for (let rightIndex = leftIndex + 1; rightIndex < sections.length; rightIndex += 1) {
      const similarity = ngramSimilarity(sections[leftIndex].text, sections[rightIndex].text);
      if (similarity >= 0.72) pairs.push({ left: sections[leftIndex].heading, right: sections[rightIndex].heading, similarity });
    }
  }
  return pairs;
}

function countTemplateSentencePatterns(text: string) {
  const patterns = [
    /本(?:课程|报告|方案|教案|文档)?(?:围绕|聚焦)[^。；;]{0,36}(?:展开|制定|推进|组织)/g,
    /目标是把[^。；;]{0,36}转化为[^。；;]{0,36}/g,
    /形成完整学习闭环/g,
    /建立可迁移的知识框架/g,
    /形成独立应用能力/g,
    /巩固学习结果/g
  ];
  return patterns.reduce((total, pattern) => total + (text.match(pattern) || []).length, 0);
}

function findLessonProcessIssue(plan: WordDocumentPlan, intent?: WordGenerationIntent) {
  if (plan.documentType !== "lesson_plan") return null;
  const anchors = groundingIntentKeywords(intent);
  const process = plan.sections.find((section) => /教学过程/.test(section.heading));
  if (!process) return "Lesson plan missing teaching process section.";
  const table = process.blocks.find((block): block is Extract<WordBlock, { type: "table" }> => block.type === "table" && block.headers.some((header) => /教师活动|学生活动|设计意图/.test(header)));
  if (!table) return "Lesson process should be a table with teacher activity, student activity, and design intent.";
  const genericFragments = ["提出问题并说明目标", "观察案例并回应问题", "完成任务输出", "依据评价标准自查", "形成独立应用能力", "巩固学习结果", "建立学习情境", "建立可迁移的知识框架"];
  const tableText = table.rows.flat().join(" ");
  const genericHits = genericFragments.filter((fragment) => tableText.includes(fragment)).length;
  const anchoredRows = anchors.length
    ? table.rows.filter((row) => {
        const rowText = compact(row.join(" "));
        return anchors.some((anchor) => rowText.includes(compact(anchor)));
      }).length
    : table.rows.length;
  if (genericHits >= 4) return "Lesson process table contains too many generic teaching actions.";
  if (table.rows.length >= 4 && anchoredRows < 3) return "Lesson process table is not grounded in enough intent anchors.";
  return null;
}

function templateForDocumentType(type?: WordGenerationIntent["documentType"]) {
  if (type === "lesson_plan") return "lesson_plan";
  if (type === "proposal") return "proposal";
  if (type === "report") return "report";
  if (type === "meeting_minutes") return "meeting_minutes";
  return "general";
}

function minimumGroundedSections(intent: WordGenerationIntent, sectionCount: number) {
  if (intent.documentType === "lesson_plan") return Math.min(4, sectionCount);
  if (intent.documentType === "report" || intent.documentType === "proposal" || intent.documentType === "business_plan" || intent.documentType === "work_summary") return Math.min(3, sectionCount);
  if (intent.documentType === "meeting_minutes" || intent.documentType === "training_plan") return Math.min(2, sectionCount);
  return Math.min(2, sectionCount);
}

function contentSectionsForGrounding(plan: WordDocumentPlan) {
  return plan.sections.filter((section) => {
    if (section.level !== 1) return false;
    return !/基本信息|会议基本信息|工作概况|背景与范围|背景与现状|适用范围|实施范围与分工|课程定位/.test(section.heading);
  });
}

function repairSection(section: WordSection, title: string): WordSection {
  const blocks = section.blocks.map((block) => {
    if (block.type === "table" && /教学过程/.test(section.heading)) {
      const headersText = block.headers.join(" ");
      if (/教师活动/.test(headersText) && /学生活动/.test(headersText) && /设计意图/.test(headersText)) return block;
      return {
        type: "table" as const,
        headers: ["教学环节", "时间", "教师活动", "学生活动", "设计意图"],
        rows: (block.rows.length ? block.rows : [["导入", "案例观察", "10 分钟"]]).map((row, index) => {
          const stage = cleanText(row[0], 40) || (index === 0 ? "任务导入" : `活动${index + 1}`);
          const content = cleanText(row[1], 80) || cleanText(row.join(" "), 80) || "课堂任务";
          const time = cleanText(row[2], 30) || "按课堂节奏";
          return [
            stage,
            time,
            `围绕${content}组织示范、追问和即时反馈。`,
            `观察${content}材料，完成记录、讨论或练习输出。`,
            `让学生把${content}转化为可说明、可检查的学习成果。`
          ];
        })
      };
    }
    if (block.type === "numbered_list" && /教学过程/.test(section.heading)) {
      return {
        type: "table" as const,
        headers: ["教学环节", "时间", "教师活动", "学生活动", "设计意图"],
        rows: block.items.map((item, index) => {
          const content = cleanText(item, 80) || `课堂活动${index + 1}`;
          return [
            content.replace(/[。；;]$/, ""),
            index === 0 ? "10 分钟" : "按课堂节奏",
            `围绕${content}组织讲解、示范或反馈。`,
            `参与${content}，完成观察、讨论或练习输出。`,
            `让学生把${content}转化为可检查的学习成果。`
          ];
        })
      };
    }
    if (block.type !== "numbered_list") return block;
    if (/过程|流程|步骤|标准|评价/.test(section.heading)) return block;
    return { type: "bullet_list" as const, items: block.items };
  });
  return {
    ...section,
    intro: cleanText(section.intro) || fallbackIntro(section, title),
    blocks
  };
}

function lessonFallbackSection(heading: string): WordSection {
  if (heading === "课程基本信息" || heading === "基本信息") {
    return {
      heading: "课程基本信息",
      level: 1,
      intro: "课程基本信息集中呈现授课条件、学习对象、课时安排和课堂组织方式，便于教师在备课前确认实施边界。",
      blocks: [
        {
          type: "table",
          headers: ["项目", "内容"],
          rows: [
            ["课程名称", "本课主题"],
            ["授课对象", "相关课程学习者"],
            ["课时", "1-2 课时"],
            ["授课方式", "讲授、示范、练习、反馈"]
          ]
        }
      ]
    };
  }
  if (heading === "设计思路") {
    return {
      heading,
      level: 1,
      intro: "设计思路说明课堂从问题进入、方法示范到练习反馈的组织逻辑，使教师能够看清每个活动与学习目标之间的关系。",
      blocks: [
        {
          type: "paragraph",
          text: "课堂应先用材料或案例唤起观察，再通过教师示范拆解关键方法，最后安排学生完成可检查的练习成果，并用反馈推动二次修正。"
        }
      ]
    };
  }
  if (heading === "教学目标") {
    return {
      heading,
      level: 1,
      intro: "教学目标需要同时覆盖知识理解、方法运用和学习反思，避免只停留在概念记忆。",
      blocks: [
        {
          type: "bullet_list",
          items: [
            "知识目标：能够说出本课核心概念、判断依据和常见误区。",
            "能力目标：能够依据示范步骤完成课堂练习，并说明自己的处理理由。",
            "素养目标：能够根据同伴和教师反馈修正成果，形成可迁移的学习方法。"
          ]
        }
      ]
    };
  }
  if (heading === "教学过程") {
    return {
      heading,
      level: 1,
      intro: "教学过程按照导入、示范、练习和反馈推进，强调从观察材料进入问题，再把知识理解转化为课堂产出。",
      blocks: [
        {
          type: "table",
          headers: ["教学环节", "时间", "教师活动", "学生活动", "设计意图"],
          rows: [
            ["任务导入", "10 分钟", "呈现与本课主题相关的材料，要求学生先记录观察到的现象和疑问。", "阅读或观察材料，写下判断依据并提出需要澄清的问题。", "让学生从真实材料进入学习任务，避免直接记忆结论。"],
            ["方法示范", "20 分钟", "拆解一个关键样例，说明判断步骤、操作要点和常见偏差。", "跟随示范完成标注、比较或初步练习，记录不理解的节点。", "把抽象要求转化为可观察、可操作的学习动作。"],
            ["课堂练习", "25 分钟", "布置小任务并巡视反馈，针对共性问题进行即时修正。", "独立完成练习并依据评价标准自查，必要时进行二次修改。", "通过输出和修改检验学生是否真正掌握方法。"],
            ["展示反馈", "10 分钟", "选择代表性成果进行点评，归纳可迁移的改进建议。", "说明自己的处理思路，记录下一步优化方向。", "用展示和反馈巩固学习结果。"]
          ]
        }
      ]
    };
  }
  return {
    heading,
    level: 1,
    intro: `${heading}需要结合课程目标形成明确的课堂证据，说明学生应完成什么、教师如何判断完成质量。`,
    blocks: [{ type: "paragraph", text: "该环节应保留可核对的活动记录、学生输出或评价依据，便于课后复盘教学效果。" }]
  };
}

const REQUIRED_SECTION_ALIASES: Array<[string[], string[]]> = [
  [["培训目标", "培训目的", "目标设计"], ["培训目标", "培训目的", "目标设计", "目标"]],
  [["培训内容", "培训模块", "课程内容"], ["培训内容", "培训模块", "课程内容", "三天流程", "三日安排", "时间安排", "培训流程", "教学安排"]],
  [["三天流程", "三日安排", "三天培训流程"], ["三天流程", "三日安排", "三天培训流程", "三天安排", "培训流程", "时间安排"]],
  [["时间安排", "日程安排", "流程安排"], ["时间安排", "日程安排", "流程安排", "三天流程", "三日安排", "培训流程"]],
  [["责任分工", "职责矩阵", "分工安排"], ["责任分工", "职责矩阵", "分工安排", "责任矩阵", "责任人", "牵头", "协作"]],
  [["考核方式", "考核评价", "评价标准"], ["考核方式", "考核评价", "评价标准", "考核标准", "评分标准", "验收标准", "评价指标"]],
  [["风险预案", "风险控制", "应急措施"], ["风险预案", "风险控制", "应急措施", "风险保障", "风险与预案"]],
  [["验收", "验收标准"], ["验收", "验收标准", "评价指标", "考核评价", "评价标准"]],
  [["目标"], ["目标", "目的"]],
  [["步骤"], ["步骤", "流程", "安排", "路径"]],
  [["风险"], ["风险", "预案", "控制", "应急"]],
  [["评价"], ["评价", "考核", "验收", "标准", "指标"]],
  [["待办"], ["待办", "任务", "行动项"]],
  [["责任人"], ["责任人", "负责人", "牵头人", "职责矩阵"]]
];

function aliasesForRequired(required: string) {
  const key = compact(required);
  const aliases = new Set<string>([required, ...splitIntentItems(required)]);
  for (const [triggers, values] of REQUIRED_SECTION_ALIASES) {
    if (triggers.some((trigger) => key.includes(compact(trigger)) || compact(trigger).includes(key))) {
      for (const value of values) aliases.add(value);
    }
  }
  return [...aliases].filter(Boolean);
}

function textMatchesRequired(text: string, required: string) {
  const normalizedText = compact(text);
  if (!normalizedText) return false;
  const aliases = aliasesForRequired(required);
  return aliases.some((alias) => {
    const key = compact(alias);
    return key.length >= 2 && (normalizedText.includes(key) || key.includes(normalizedText));
  });
}

function sectionMatchesRequired(section: WordSection, required: string) {
  return textMatchesRequired(textFromSection(section), required);
}

function planMatchesRequired(plan: WordDocumentPlan, required: string) {
  return plan.sections.some((section) => sectionMatchesRequired(section, required));
}

function sectionHeadingMatchesRequired(section: WordSection, required: string) {
  return textMatchesRequired(section.heading, required);
}

function planHasRequiredHeading(plan: WordDocumentPlan, required: string) {
  return plan.sections.some((section) => sectionHeadingMatchesRequired(section, required));
}

function requiredHeading(required: string) {
  const aliases = aliasesForRequired(required);
  return cleanText(aliases[0] || required, 40);
}

function requiredFallbackSection(required: string, plan: WordDocumentPlan, intent?: WordGenerationIntent): WordSection {
  const heading = requiredHeading(required);
  const topic = cleanText(intent?.topic || plan.title, 80) || "文档主题";
  const aliases = aliasesForRequired(required).join("、");
  if (textMatchesRequired(heading, "三天流程") || textMatchesRequired(heading, "时间安排")) {
    const dayRows = /三天|三日/.test(required)
      ? [
          ["第一天", "组织认知、制度说明和入职流程熟悉", "完成入职学习记录"],
          ["第二天", "岗位流程演示、导师带教和场景练习", "完成岗位练习任务"],
          ["第三天", "综合演练、答疑复盘和考核确认", "形成考核结果与改进清单"]
        ]
      : [
          ["启动阶段", `明确${topic}的目标、参与对象和执行边界`, "任务清单"],
          ["执行阶段", `推进${aliases}对应任务并记录问题`, "过程记录"],
          ["复盘阶段", `核对${topic}完成质量并沉淀改进项`, "复盘清单"]
        ];
    return {
      heading: /三天|三日/.test(required) ? "三天培训流程与时间安排" : heading,
      level: 1,
      intro: `${heading}用于把${topic}拆成可执行、可检查的阶段，避免只写原则而缺少落地节奏。`,
      blocks: [{ type: "timeline", headers: ["阶段", "安排", "产出"], rows: dayRows }]
    };
  }
  if (textMatchesRequired(heading, "责任分工")) {
    return {
      heading: "责任分工",
      level: 1,
      intro: `责任分工明确${topic}推进过程中的牵头、协作和交付边界，便于执行中快速确认责任。`,
      blocks: [
        {
          type: "responsibility_matrix",
          headers: ["事项", "牵头", "协作", "交付物"],
          rows: [
            [topic, "任务负责人", "执行协作人员", "执行记录与阶段成果"],
            [heading, "模块负责人", "协作团队", "检查清单与反馈记录"]
          ]
        }
      ]
    };
  }
  if (textMatchesRequired(heading, "考核方式")) {
    return {
      heading: "考核方式与评价标准",
      level: 1,
      intro: `考核方式围绕${topic}的实际完成质量设计，既看结果，也看过程记录和改进反馈。`,
      blocks: [
        {
          type: "rubric",
          headers: ["评价项目", "比例", "标准"],
          rows: [
            ["理解掌握", "建议30%（可按实际调整）", `能准确说明${topic}的关键流程和执行要求。`],
            ["任务完成", "建议50%（可按实际调整）", "能按要求完成核心任务并保留过程记录。"],
            ["复盘改进", "建议20%（可按实际调整）", "能根据反馈提出具体改进动作。"]
          ]
        }
      ]
    };
  }
  if (textMatchesRequired(heading, "风险预案")) {
    return {
      heading: "风险预案",
      level: 1,
      intro: `风险预案用于提前处理${topic}推进中可能出现的时间冲突、资源不足、协同不畅和验收偏差。`,
      blocks: [
        {
          type: "checklist",
          items: [
            "提前确认关键人员、时间和材料是否到位。",
            "每日记录阻塞问题并明确责任人与解决期限。",
            "对影响交付质量的风险安排补救措施和复盘机制。"
          ]
        }
      ]
    };
  }
  return {
    heading,
    level: 1,
    intro: `${heading}是用户明确要求的交付模块，本节围绕${topic}说明目标、执行方式和检查依据。`,
    blocks: [
      {
        type: "table",
        headers: ["模块", "落实方式", "检查依据"],
        rows: [[heading, `围绕${topic}补齐${aliases}对应的执行内容。`, "形成可核对的记录、表格或任务清单。"]]
      }
    ]
  };
}

function appendMissingRequiredSections(plan: WordDocumentPlan, fallbackPlan: WordDocumentPlan, intent?: WordGenerationIntent) {
  const required =
    plan.documentType === "lesson_plan"
      ? REQUIRED_LESSON_SECTIONS
      : plan.documentType
        ? REQUIRED_SECTIONS_BY_TYPE[plan.documentType] || []
        : [];
  const explicitRequired = (intent?.mustInclude || []).filter((item) => !isDeliveryOrStyleRequirement(item));
  if (!required.length && !explicitRequired.length) return plan.sections;

  const sections = [...plan.sections];
  for (const requiredHeading of required) {
    if (sections.some((section) => sectionHeadingMatchesRequired(section, requiredHeading))) continue;
    const fallbackSection = fallbackPlan.sections.find((section) => sectionHeadingMatchesRequired(section, requiredHeading));
    sections.push(fallbackSection || requiredFallbackSection(requiredHeading, plan, intent));
  }
  for (const requiredHeading of explicitRequired) {
    if (sections.some((section) => sectionMatchesRequired(section, requiredHeading))) continue;
    const fallbackSection = fallbackPlan.sections.find((section) => sectionMatchesRequired(section, requiredHeading));
    sections.push(fallbackSection || requiredFallbackSection(requiredHeading, plan, intent));
  }
  return sections;
}

function appendMissingIntentSummary(plan: WordDocumentPlan, intent: WordGenerationIntent, report: WordQualityReport) {
  if (!report.keywordCoverage.missingKeywords.length) return plan.sections;
  const missing = report.keywordCoverage.missingKeywords.slice(0, 8);
  return [
    ...plan.sections,
    {
      heading: "需求约束补充",
      level: 1 as const,
      intro: `本节用于补充生成结果中需要明确回应的用户约束，确保文档仍围绕${intent.topic}展开并覆盖关键交付条件。`,
      blocks: [
        {
          type: "table" as const,
          headers: ["约束项", "落实方式"],
          rows: missing.map((keyword) => [keyword, `在${intent.topic}相关执行、分析或验收内容中持续核对该要求。`])
        }
      ]
    }
  ];
}

export function evaluateWordDocumentPlan(
  plan: WordDocumentPlan,
  context: { intent?: WordGenerationIntent; prompt?: string } = {}
): WordQualityReport {
  const issues: WordQualityIssue[] = [];
  const text = textFromPlan(plan);
  const compactText = compact(text);
  const keywordCoverage = getWordIntentKeywordCoverage(plan, context.intent);
  if (/Generated by NexusAI|由\s*NexusAI\s*生成|NexusAI/i.test(text)) {
    issues.push({ code: "platform_signature", message: "Document contains platform signature text.", severity: "high" });
  }

  const shouldEnforceIntent = Boolean(context.prompt);

  if (shouldEnforceIntent && context.intent && !isUsableWordIntent(context.intent)) {
    issues.push({ code: "insufficient_intent", message: "Word generation intent lacks a usable topic.", severity: "high" });
  }

  if (context.prompt) {
    const promptText = compact(context.prompt);
    if (promptText.length > 18 && compact(plan.title).includes(promptText.slice(0, Math.min(promptText.length, 40)))) {
      issues.push({ code: "title_uses_prompt", message: "Document title appears to use the full prompt.", severity: "high" });
    }
    if (promptText.length > 24 && compactText.includes(promptText)) {
      issues.push({ code: "prompt_echo", message: "Document body repeats the user prompt verbatim.", severity: "high" });
    }
  }

  if (plan.title.length > 44 || /给我|帮我|生成|输出|导出|要求|授课对象|范围/.test(plan.title)) {
    issues.push({ code: "title_uses_prompt", message: "Document title is too long or contains task words.", severity: "high" });
  }
  if (isTemplateLabelTitle(plan.title)) {
    issues.push({ code: "template_title", message: "Document title uses an internal template label.", severity: "high" });
  }

  for (const smell of TEMPLATE_SMELLS) {
    if (text.includes(smell)) {
      issues.push({ code: "template_text", message: `Document contains template text: ${smell}`, severity: "high" });
    }
  }

  const protectedKeywords = significantIntentKeywords(context.intent).map(compact);
  for (const [phrase, count] of countRepeatedPhrases(text)) {
    if (protectedKeywords.some((keyword) => keyword.includes(compact(phrase)) || compact(phrase).includes(keyword))) continue;
    issues.push({ code: "repeated_phrase", message: `Phrase "${phrase}" repeats ${count} times.`, severity: "medium" });
  }

  const templatePatternCount = countTemplateSentencePatterns(text);
  if (templatePatternCount >= 4) {
    issues.push({ code: "template_text", message: `Document contains ${templatePatternCount} template-like sentence patterns.`, severity: "high" });
  }

  for (const pair of findHighlySimilarSections(plan).slice(0, 2)) {
    issues.push({
      code: "section_similarity",
      message: `Sections "${pair.left}" and "${pair.right}" are too similar (${pair.similarity.toFixed(2)}).`,
      severity: "high"
    });
  }

  const lessonProcessIssue = findLessonProcessIssue(plan, context.intent);
  if (lessonProcessIssue) {
    issues.push({ code: "generic_lesson_process", message: lessonProcessIssue, severity: "high" });
  }

  if (shouldEnforceIntent) {
    for (const keyword of keywordCoverage.missingKeywords) {
      const isCoreMissing = keywordCoverage.missingCoreKeywords.some((item) => compact(item) === compact(keyword));
      const isMustIncludeMissing = isExplicitMustIncludeKeyword(context.intent, keyword);
      issues.push({
        code: "missing_intent_keyword",
        message: `Document missing intent keyword: ${keyword}`,
        severity: isCoreMissing || isMustIncludeMissing ? "high" : "medium"
      });
    }
    if (context.intent && isUsableWordIntent(context.intent)) {
      const anchors = groundingIntentKeywords(context.intent);
      const sections = contentSectionsForGrounding(plan);
      const hasSpecificGroundingConstraints = Boolean(
        context.intent.scope ||
          context.intent.chapter ||
          context.intent.chapterTitle ||
          context.intent.purpose ||
          context.intent.mustInclude.length ||
          context.intent.requirements.length
      );
      if (hasSpecificGroundingConstraints && anchors.length >= 2 && sections.length) {
        const groundedSections = sections.filter((section) => {
          const sectionText = compact(textFromSection(section));
          const hitCount = anchors.reduce((count, keyword) => count + (keywordMatches(sectionText, keyword) ? 1 : 0), 0);
          return hitCount >= 2;
        });
        const requiredSections = minimumGroundedSections(context.intent, sections.length);
        if (groundedSections.length < requiredSections) {
          issues.push({
            code: "weak_intent_grounding",
            message: `Only ${groundedSections.length}/${sections.length} content sections are grounded in intent anchors.`,
            severity: "high"
          });
        }
      }
    }
  }

  const weakSections = plan.sections.filter((section) => section.level === 1 && !sectionHasBody(section));
  for (const section of weakSections) {
    issues.push({ code: "heading_without_body", message: `Section "${section.heading}" has no narrative body.`, severity: "high" });
  }
  for (const section of plan.sections.filter((section) => section.level === 1 && sectionStartsWithUnsupportedList(section))) {
    issues.push({ code: "heading_without_body", message: `Section "${section.heading}" starts with a list without narrative.`, severity: "high" });
  }

  if (countUnsupportedNumberedLists(plan) >= 4) {
    issues.push({ code: "too_many_numbered_lists", message: "Document contains too many numbered lists outside step/process sections.", severity: "medium" });
  }

  const hasParagraph = plan.sections.some((section) => Boolean(section.intro) || section.blocks.some((block) => block.type === "paragraph"));
  const hasList = hasBlockType(plan, "bullet_list") || hasBlockType(plan, "numbered_list") || hasBlockType(plan, "checklist");
  const hasTable = hasTableLikeBlock(plan);
  if (!hasParagraph || !hasList || !hasTable) {
    issues.push({ code: "missing_structure_mix", message: "Document should include headings, paragraphs, and table/list structures.", severity: "medium" });
  }

  const placeholderCount = countPlaceholderTerms(text);
  if (placeholderCount >= 3) {
    issues.push({ code: "placeholder_content", message: `Document contains ${placeholderCount} placeholder-like terms.`, severity: "high" });
  }

  const unsupportedSpecificDataCount = countUnsupportedSpecificData(text);
  if (unsupportedSpecificDataCount >= 3) {
    issues.push({ code: "unsupported_specific_data", message: `Document contains ${unsupportedSpecificDataCount} unqualified specific numbers.`, severity: "high" });
  }

  if (plan.documentType === "lesson_plan") {
    for (const required of REQUIRED_LESSON_SECTIONS) {
      if (!planHasRequiredHeading(plan, required)) {
        issues.push({ code: "lesson_plan_missing_required_section", message: `Lesson plan missing ${required}.`, severity: "high" });
      }
    }
  }

  const requiredSections = plan.documentType ? REQUIRED_SECTIONS_BY_TYPE[plan.documentType] : undefined;
  if (requiredSections?.length && plan.sections.length >= Math.min(5, requiredSections.length)) {
    for (const required of requiredSections) {
      if (!planHasRequiredHeading(plan, required)) {
        issues.push({ code: "missing_required_section", message: `${plan.documentType} missing ${required}.`, severity: "high" });
      }
    }
  }

  if (context.intent?.mustInclude.length) {
    for (const required of context.intent.mustInclude.filter((item) => !isDeliveryOrStyleRequirement(item))) {
      if (!planMatchesRequired(plan, required)) {
        issues.push({ code: "missing_required_section", message: `Missing user required module: ${required}.`, severity: "high" });
      }
    }
  }

  if (context.intent?.documentType === "lesson_plan" && plan.documentType !== "lesson_plan") {
    issues.push({ code: "document_type_mismatch", message: "Lesson plan intent rendered as a non-lesson document.", severity: "high" });
  }
  if (context.intent?.documentType === "report" && plan.documentType === "lesson_plan") {
    issues.push({ code: "document_type_mismatch", message: "Report intent rendered as lesson plan.", severity: "high" });
  }

  const penalty = issues.reduce((total, issue) => total + (issue.severity === "high" ? 24 : issue.severity === "medium" ? 14 : 6), 0);
  const score = Math.max(0, 100 - penalty);
  const missingKeywordIssues = issues.filter((issue) => issue.code === "missing_intent_keyword");
  const nonKeywordIssues = issues.filter((issue) => issue.code !== "missing_intent_keyword");
  const allowedMissingKeywordCount = Math.max(1, Math.ceil(keywordCoverage.totalKeywords * 0.2));
  const onlyMinorKeywordGaps =
    issues.length > 0 &&
    nonKeywordIssues.length === 0 &&
    missingKeywordIssues.every((issue) => issue.severity !== "high") &&
    keywordCoverage.coreMatched &&
    keywordCoverage.coverageScore >= 65 &&
    keywordCoverage.missingCoreKeywords.length === 0 &&
    missingKeywordIssues.length <= allowedMissingKeywordCount;
  return {
    keywordCoverage,
    score,
    issues,
    shouldRepair: issues.length > 0 && !onlyMinorKeywordGaps
  };
}

export function canDeliverWordDocumentPlan(report: WordQualityReport) {
  if (!report.shouldRepair) return true;
  const highIssues = report.issues.filter((issue) => issue.severity === "high");
  if (highIssues.length) return false;
  const onlyKeywordIssues = report.issues.length > 0 && report.issues.every((issue) => issue.code === "missing_intent_keyword");
  return (
    onlyKeywordIssues &&
    report.keywordCoverage.coreMatched &&
    report.keywordCoverage.missingCoreKeywords.length === 0 &&
    report.keywordCoverage.coverageScore >= 60 &&
    report.score >= 55
  );
}

export function repairWordDocumentPlan(
  plan: WordDocumentPlan,
  context: { intent?: WordGenerationIntent; prompt?: string; preserveExistingPlan?: boolean } = {}
): WordDocumentPlan {
  if (context.prompt && context.intent && isUsableWordIntent(context.intent) && !context.preserveExistingPlan) {
    return buildWordDocumentPlanFromIntent(context.intent, templateForDocumentType(context.intent.documentType));
  }
  const fallbackPlan =
    context.intent && isUsableWordIntent(context.intent)
      ? buildWordDocumentPlanFromIntent(context.intent, templateForDocumentType(context.intent.documentType))
      : null;
  const report = evaluateWordDocumentPlan(plan, { intent: context.intent, prompt: context.prompt });

  const repaired: WordDocumentPlan = {
    ...plan,
    title: cleanText(plan.title, 90) || "正式文档",
    subtitle: cleanText(plan.subtitle, 120) || undefined,
    documentType: plan.documentType || fallbackPlan?.documentType,
    sections: plan.sections.map((section) => repairSection(section, plan.title))
  };

  if (fallbackPlan) {
    const titleNeedsReplacement = isTemplateLabelTitle(plan.title) || report.issues.some((issue) => issue.code === "title_uses_prompt" || issue.code === "template_title");
    repaired.title = titleNeedsReplacement ? fallbackPlan.title : cleanText(plan.title, 90) || fallbackPlan.title;
    repaired.subtitle = cleanText(plan.subtitle, 120) || fallbackPlan.subtitle;
    repaired.sections = appendMissingRequiredSections(repaired, fallbackPlan, context.intent);
  } else if (repaired.documentType === "lesson_plan") {
    repaired.sections = appendMissingRequiredSections(repaired, { ...repaired, sections: REQUIRED_LESSON_SECTIONS.map(lessonFallbackSection) }, context.intent);
  }

  if (context.intent && isUsableWordIntent(context.intent)) {
    repaired.sections = appendMissingIntentSummary(repaired, context.intent, report);
  }

  if (!hasTableLikeBlock(repaired)) {
    repaired.sections[0]?.blocks.push({
      type: "table",
      headers: ["项目", "说明"],
      rows: [["主题", repaired.title], ["用途", "整理关键背景、主要内容和后续行动"]]
    });
  }

  if (!hasBlockType(repaired, "bullet_list") && !hasBlockType(repaired, "numbered_list") && !hasBlockType(repaired, "checklist")) {
    repaired.sections[0]?.blocks.push({
      type: "bullet_list",
      items: ["明确文档目标", "补充关键事实", "形成可执行结论"]
    });
  }

  return repaired;
}
