import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { createLocalPresentationProvider, preparePresentationDeckV3 } from "../lib/presentation/providers/local";
import { buildVisualPresentationPlan } from "../lib/presentation/v2/visual-plan";

function assert(condition: unknown, label: string): asserts condition {
  if (!condition) throw new Error(label);
}

function listZipEntries(buffer: Buffer) {
  const entries: string[] = [];
  for (let offset = 0; offset <= buffer.length - 46; offset += 1) {
    if (buffer.readUInt32LE(offset) !== 0x02014b50) continue;
    const nameLength = buffer.readUInt16LE(offset + 28);
    const extraLength = buffer.readUInt16LE(offset + 30);
    const commentLength = buffer.readUInt16LE(offset + 32);
    const nameStart = offset + 46;
    const nameEnd = nameStart + nameLength;
    if (nameEnd > buffer.length) break;
    entries.push(buffer.subarray(nameStart, nameEnd).toString("utf8"));
    offset = nameEnd + extraLength + commentLength - 1;
  }
  return entries;
}

const output = resolve(process.cwd(), "tmp", "ppt-v3-academic-render-test.pptx");
rmSync(output, { force: true });

const deck = {
  title: "MambaOut Paper Talk",
  style: "academic" as const,
  theme: "research_report",
  slides: [
    { type: "cover" as const, layoutPreset: "academic_cover" as const, title: "MambaOut: Do We Really Need Mamba for Vision?", subtitle: "A paper-style academic presentation", visualBrief: "Academic cover with method figure and result cards" },
    { type: "agenda" as const, layoutPreset: "agenda_list" as const, title: "Roadmap", bullets: ["Motivation", "Architecture", "Experiments", "Conclusion"] },
    { type: "imageText" as const, layoutPreset: "image_explanation" as const, title: "Main Hypothesis", bullets: ["Sequence modeling may not be necessary for every vision stage", "Controlled baselines reveal where complexity helps", "A simpler block can improve speed and interpretability"], visualBrief: "Model architecture comparison diagram", imageQuery: "MambaOut vision model comparison figure" },
    { type: "timeline" as const, layoutPreset: "process_steps" as const, title: "Method Pipeline", bullets: ["Patch embedding", "Feature mixing", "Stage stacking", "Prediction head"] },
    { type: "comparison" as const, layoutPreset: "comparison_matrix" as const, title: "Method Comparison", bullets: ["Mamba: stronger sequence prior", "Mamba: higher implementation cost", "MambaOut: simpler visual mixer", "MambaOut: competitive trade-off"] },
    { type: "data" as const, layoutPreset: "data_insight" as const, title: "Experimental Results", metrics: [{ label: "Top-1", value: "84.1%", detail: "Illustrative controlled result" }, { label: "Throughput", value: "+18%", detail: "Relative improvement" }] },
    { type: "closing" as const, layoutPreset: "summary_closing" as const, title: "Takeaways", bullets: ["Keep strong baselines", "Measure complexity trade-offs", "Use Mamba where evidence supports it"] }
  ]
};

async function main() {
  const visualPlan = buildVisualPresentationPlan(deck, { theme: "academic_paper" });
  const preparedDeck = await preparePresentationDeckV3(deck, visualPlan, { fallbackToV2: true });
  const provider = createLocalPresentationProvider();
  const result = await provider.generate({ deck: preparedDeck });

  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, result.buffer);

  assert(existsSync(output), "Expected rendered PPTX file to exist");
  assert(result.buffer.subarray(0, 2).toString("utf8") === "PK", "Expected PPTX ZIP package");
  assert(listZipEntries(result.buffer).filter((entry) => /^ppt\/slides\/slide\d+\.xml$/.test(entry)).length === deck.slides.length, "V3 render should preserve slide count");

  const xml = readFileSync(output).toString("utf8");
  assert(xml.includes("V3 Academic Paper Rendered"), "Expected V3 rendered marker");
  assert(xml.includes("V3 Paper Card") || xml.includes("V3 Paper Figure") || xml.includes("V3 Paper Chart"), "Expected V3 card/figure/chart shapes");
  assert(xml.includes("V2 Preset Rendered") === false, "V3 render should not fall back to V2 for this deck");
  assert(!xml.includes("Generated by NexusAI"), "Generated PPTX should not expose English platform signature");
  assert(!xml.includes("由 NexusAI 生成"), "Generated PPTX should not expose Chinese platform signature");

  console.log(JSON.stringify({ ok: true, output, slides: deck.slides.length, sizeBytes: result.buffer.length }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
