import { writeFileSync, mkdirSync, rmSync } from "node:fs";
import { dirname, resolve } from "node:path";

import { createLocalPresentationProvider, preparePresentationDeckV3 } from "../lib/presentation/providers/local";
import { buildVisualPresentationPlan } from "../lib/presentation/v2/visual-plan";

function assert(condition: unknown, label: string): asserts condition {
  if (!condition) throw new Error(label);
}

function listZipEntries(buffer: Buffer) {
  const entries: string[] = [];
  for (let offset = 0; offset <= buffer.length - 46; offset += 1) {
    if (buffer.readUInt32LE(offset) !== 0x02014b50) continue;
    const nameLength = buffer.readUInt16LE(offset + 28);
    const extraLength = buffer.readUInt16LE(offset + 30);
    const commentLength = buffer.readUInt16LE(offset + 32);
    const nameStart = offset + 46;
    const nameEnd = nameStart + nameLength;
    if (nameEnd > buffer.length) break;
    entries.push(buffer.subarray(nameStart, nameEnd).toString("utf8"));
    offset = nameEnd + extraLength + commentLength - 1;
  }
  return entries;
}

function readZipEntry(buffer: Buffer, entryName: string) {
  for (let offset = 0; offset <= buffer.length - 30; offset += 1) {
    if (buffer.readUInt32LE(offset) !== 0x04034b50) continue;
    const compressedSize = buffer.readUInt32LE(offset + 18);
    const nameLength = buffer.readUInt16LE(offset + 26);
    const extraLength = buffer.readUInt16LE(offset + 28);
    const nameStart = offset + 30;
    const nameEnd = nameStart + nameLength;
    const name = buffer.subarray(nameStart, nameEnd).toString("utf8");
    const contentStart = nameEnd + extraLength;
    const contentEnd = contentStart + compressedSize;
    if (name === entryName) return buffer.subarray(contentStart, contentEnd).toString("utf8");
    offset = contentEnd - 1;
  }
  return "";
}

const deck = {
  title: "V3 Speaker Notes Check",
  style: "academic" as const,
  theme: "research_report",
  slides: [
    {
      type: "cover" as const,
      layoutPreset: "academic_cover" as const,
      title: "MambaOut: Do We Really Need Mamba for Vision?",
      subtitle: "Paper-style academic presentation",
      visualBrief: "Cover visual with architecture and benchmark context",
      speakerNotes: "Opening notes: introduce the paper question and explain why this comparison matters."
    },
    {
      type: "imageText" as const,
      layoutPreset: "image_explanation" as const,
      title: "Core Hypothesis",
      bullets: [
        "Simpler visual mixers can remain competitive under controlled comparison.",
        "Sequence-style memory should be justified by task evidence.",
        "The baseline must separate module effect from training recipe."
      ],
      visualBrief: "Mechanism diagram comparing sequence memory and visual hierarchy"
    },
    {
      type: "timeline" as const,
      layoutPreset: "process_steps" as const,
      title: "Method Pipeline",
      bullets: ["Patch embedding", "Feature mixing", "Stage stacking", "Prediction head"]
    }
  ]
};

async function main() {
  const output = resolve(process.cwd(), "tmp", "ppt-v3-speaker-notes-test.pptx");
  rmSync(output, { force: true });

  const visualPlan = buildVisualPresentationPlan(deck, { theme: "academic_paper" });
  const preparedDeck = await preparePresentationDeckV3(deck, visualPlan, { fallbackToV2: true });
  const result = await createLocalPresentationProvider().generate({ deck: preparedDeck });

  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, result.buffer);

  const entries = listZipEntries(result.buffer);
  const noteEntries = entries.filter((entry) => /^ppt\/notesSlides\/notesSlide\d+\.xml$/.test(entry));
  assert(noteEntries.length === deck.slides.length, `Expected one notes slide per page, got ${noteEntries.length}`);

  const noteTexts = noteEntries.map((entry) => readZipEntry(result.buffer, entry));
  const nonEmptyNotes = noteTexts.filter((xml) => /<a:t>[^<]{12,}<\/a:t>/.test(xml)).length;
  assert(nonEmptyNotes / deck.slides.length >= 0.9, `Expected at least 90% non-empty notes, got ${nonEmptyNotes}/${deck.slides.length}`);
  assert(noteTexts.some((xml) => xml.includes("Opening notes") || xml.includes("Core Hypothesis")), "Expected notes XML to contain slide title or speaker notes keyword");

  const packageText = result.buffer.toString("utf8");
  assert(!packageText.includes("Generated by NexusAI"), "Notes package should not contain English platform signature");
  assert(!packageText.includes("由 NexusAI 生成"), "Notes package should not contain Chinese platform signature");
  assert(!packageText.includes("NexusAI 智能文档模块"), "Notes package should not contain document module signature");

  console.log(JSON.stringify({ ok: true, output, notesSlides: noteEntries.length, nonEmptyNotes }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
