import { buildVisualPresentationPlan } from "../lib/presentation/v2/visual-plan";

function assert(condition: unknown, label: string): asserts condition {
  if (!condition) throw new Error(label);
}

const deck = {
  title: "Paper Talk Visual Plan",
  style: "academic",
  slides: [
    { type: "cover", layoutPreset: "academic_cover", title: "MambaOut: Do We Really Need Mamba for Vision?", subtitle: "Paper reading and method discussion", visualBrief: "Academic paper cover with model diagram and result cards" },
    { type: "agenda", layoutPreset: "agenda_list", title: "Talk Roadmap", bullets: ["Motivation", "Method intuition", "Experiments", "Takeaways"] },
    { type: "imageText", layoutPreset: "image_explanation", title: "Core Observation", bullets: ["Vision tasks rely on local texture and hierarchical features", "Mamba-like sequence modeling is not always the decisive factor", "Empirical comparisons clarify when simpler blocks are enough"], visualBrief: "Paper figure area showing model comparison", imageQuery: "MambaOut vision model paper architecture figure" },
    { type: "timeline", layoutPreset: "process_steps", title: "Method Pipeline", bullets: ["Patch embedding", "Feature mixing", "Stage stacking", "Classifier head"] },
    { type: "comparison", layoutPreset: "comparison_matrix", title: "Architecture Comparison", bullets: ["Mamba: sequence state space block", "ConvNet: local inductive bias", "MambaOut: simplified mixer", "Result: competitive trade-off"] },
    { type: "data", layoutPreset: "data_insight", title: "Experiment Results", metrics: [{ label: "ImageNet", value: "84.1%", detail: "Top-1 accuracy" }, { label: "Throughput", value: "+18%", detail: "Relative speed" }] },
    { type: "closing", layoutPreset: "summary_closing", title: "Takeaways", bullets: ["Question the necessity of complex blocks", "Compare under controlled settings", "Use simpler baselines when they are sufficient"] }
  ]
};

const visualPlan = buildVisualPresentationPlan(deck, { theme: "academic_paper" });
const visualKinds = new Set(["text_card", "callout_card", "figure_panel", "image_panel", "comparison_table", "process_diagram", "timeline", "bar_chart", "metric_card", "takeaway"]);
const slidesWithVisualBlocks = visualPlan.slides.filter((slide) => slide.blocks.some((block) => visualKinds.has(block.kind))).length;
const allText = JSON.stringify(visualPlan);

assert(visualPlan.theme === "academic_paper", "Expected academic paper theme");
assert(visualPlan.slides.length === deck.slides.length, "Visual plan should preserve slide count");
for (const slide of visualPlan.slides) {
  assert(slide.blocks.length > 0, `Slide ${slide.slideIndex} should have visual blocks`);
  assert(slide.blocks.some((block) => block.kind === "title"), `Slide ${slide.slideIndex} should have a title block`);
}
assert(slidesWithVisualBlocks / visualPlan.slides.length >= 0.8, "At least 80% of slides should have non-text visual blocks");
assert(!allText.includes("Generated by NexusAI"), "Visual plan should not include English platform signature");
assert(!allText.includes("由 NexusAI 生成"), "Visual plan should not include Chinese platform signature");

console.log(JSON.stringify({ ok: true, slides: visualPlan.slides.length, visualSlides: slidesWithVisualBlocks }, null, 2));
