import { createDocxBuffer } from "@/lib/document/create";
import { parseDocxPackage } from "@/lib/document/docx-package";

function assert(condition: unknown, label: string): asserts condition {
  if (!condition) throw new Error(label);
}

function textFromXml(xml: string) {
  return xml
    .replace(/<[^>]+>/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

function tableColumnWidths(xml: string) {
  const firstTable = xml.match(/<w:tbl>[\s\S]*?<\/w:tbl>/)?.[0] || "";
  return [...firstTable.matchAll(/<w:gridCol w:w="(\d+)"\/>/g)].map((match) => Number(match[1]));
}

function main() {
  const markdown = `WORD_DOCUMENT_PLAN_JSON
{
  "title": "校园低碳行动实施方案",
  "subtitle": "三个月执行计划",
  "documentType": "proposal",
  "sections": [
    {
      "heading": "方案目标",
      "level": 1,
      "intro": "本方案用于组织后勤处和学生社团在三个月内推进校园低碳行动。",
      "blocks": [
        {
          "type": "responsibility_matrix",
          "headers": ["事项", "执行说明", "责任部门", "验收标准"],
          "rows": [
            ["节能巡检", "按楼栋建立巡检清单，记录高耗能设备和整改状态。", "后勤处", "形成每周巡检记录并完成问题闭环。"],
            ["旧物回收", "设置回收点并安排志愿者分类登记。", "学生社团", "回收数据可核对，活动后形成复盘。"]
          ]
        }
      ]
    },
    {
      "heading": "实施步骤",
      "level": 1,
      "intro": "执行步骤按照启动、推进、检查和复盘组织。",
      "blocks": [{ "type": "numbered_list", "items": ["发布通知并明确分工。", "完成巡检和宣传。", "汇总数据并复盘。"] }]
    },
    {
      "heading": "时间安排",
      "level": 1,
      "intro": "时间安排覆盖三个月推进周期。",
      "blocks": [{ "type": "timeline", "headers": ["阶段", "时间", "重点任务"], "rows": [["启动", "第1周", "确认责任分工"], ["执行", "第2-10周", "持续巡检与宣传"], ["复盘", "第11-12周", "汇总成效"]] }]
    },
    {
      "heading": "资源配置",
      "level": 1,
      "intro": "资源配置需要保障人员、场地和数据记录工具。",
      "blocks": [{ "type": "paragraph", "text": "后勤处负责设施数据，学生社团负责志愿者组织，宣传材料由双方共同确认。" }]
    },
    {
      "heading": "风险预案",
      "level": 1,
      "intro": "风险预案用于保障执行不断档。",
      "blocks": [{ "type": "callout", "title": "重点提示", "text": "如遇参与度不足，应及时调整宣传节奏并补充现场引导。" }]
    },
    {
      "heading": "验收标准",
      "level": 1,
      "intro": "验收标准用于判断行动是否可复盘、可改进。",
      "blocks": [{ "type": "rubric", "headers": ["指标", "达标要求", "证据"], "rows": [["巡检覆盖", "重点楼栋全覆盖", "巡检表"], ["宣传触达", "覆盖主要社团", "活动记录"]] }]
    }
  ]
}`;

  const buffer = createDocxBuffer({
    markdown,
    title: "校园低碳行动实施方案",
    template: "proposal",
    prompt: "写一份《校园低碳行动》实施方案，周期3个月，对象为后勤处和学生社团",
  });
  const docx = parseDocxPackage(buffer);
  const documentXml = docx.getText("word/document.xml") || "";
  const documentText = textFromXml(documentXml);
  const footerXml = docx.getText("word/footer1.xml") || "";
  const relsXml = docx.getText("word/_rels/document.xml.rels") || "";
  const contentTypesXml = docx.getText("[Content_Types].xml") || "";
  const widths = tableColumnWidths(documentXml);

  assert(!/DocTemplate/.test(documentText), "Internal template markers must not appear in document text.");
  assert(documentXml.includes("<w:footerReference"), "Generated formal documents should reference a footer.");
  assert(footerXml.includes("PAGE"), "Footer should include a Word PAGE field for page numbers.");
  assert(relsXml.includes("footer1.xml"), "Document relationships should include footer1.xml.");
  assert(contentTypesXml.includes("footer+xml"), "Content types should include footer override.");
  assert(documentText.includes("章节概览"), "Multi-section formal documents should include a compact section overview.");
  assert(widths.length === 4, `Expected four table columns, got ${widths.join(",")}`);
  assert(new Set(widths).size > 1, `Responsibility matrix should not use equal column widths: ${widths.join(",")}`);
  assert(!/NexusAI|Generated by NexusAI/i.test(documentText), "Document must not include platform signature.");

  console.log(JSON.stringify({ ok: true, bytes: buffer.length, widths }, null, 2));
}

try {
  main();
} catch (error) {
  console.error(error);
  process.exitCode = 1;
}
