import { createDocxBuffer } from "@/lib/document/create";
import { parseDocxPackage } from "@/lib/document/docx-package";

function assert(condition: unknown, label: string): asserts condition {
  if (!condition) throw new Error(label);
}

function main() {
  const markdown = `# 项目复盘报告

## 背景说明

1. 项目已完成第一阶段交付。
2. 团队积累了多个流程问题。
3. 后续需要形成稳定改进方案。

## 改进步骤

1. 收集问题。
2. 分类分析。
3. 制定行动。

| 模块 | 结论 |
| --- | --- |
| 流程 | 需要统一入口 |
| 协作 | 需要明确负责人 |
`;

  const buffer = createDocxBuffer({ markdown, title: "项目复盘报告", template: "report" });
  const docx = parseDocxPackage(buffer);
  const documentXml = docx.getText("word/document.xml") || "";

  assert(documentXml.includes("背景说明"), "Expected background heading");
  assert(documentXml.includes("项目已完成第一阶段交付"), "Expected source content");
  assert(documentXml.includes("<w:tbl>"), "Expected table");
  assert(documentXml.includes("<w:ind w:firstLine="), "Expected natural paragraph first-line indent");
  assert(!/Generated by NexusAI|由\s*NexusAI\s*生成|NexusAI\s*智能文档模块/i.test(documentXml), "DOCX should not include platform signature");

  const numberedParagraphCount = (documentXml.match(/<w:numId w:val="2"\/>/g) || []).length;
  const bulletParagraphCount = (documentXml.match(/<w:numId w:val="1"\/>/g) || []).length;
  assert(numberedParagraphCount <= 3, `Only process-like lists should remain numbered, got ${numberedParagraphCount}`);
  assert(bulletParagraphCount >= 1, "General numbered outline should be converted away from document-wide numbering");

  console.log(JSON.stringify({ ok: true, numberedParagraphCount, bulletParagraphCount, bytes: buffer.length }, null, 2));
}

try {
  main();
} catch (error) {
  console.error(error);
  process.exitCode = 1;
}
