import { createDocxBuffer } from "@/lib/document/create";
import { parseDocxPackage } from "@/lib/document/docx-package";

function assert(condition: unknown, label: string): asserts condition {
  if (!condition) throw new Error(label);
}

function textFromXml(xml: string) {
  return xml.replace(/<[^>]+>/g, "").replace(/\s+/g, " ").trim();
}

function main() {
  const topics = [
    ["增长渠道", "渠道投放回收周期拉长，线索来源需要重新分层。", "复核投放批次、线索质量和转化口径，建立渠道分级看板。"],
    ["会员留存", "老会员复购出现波动，权益提醒和服务触达不够稳定。", "拆分活跃、沉默和流失预警人群，安排差异化运营动作。"],
    ["订单履约", "高峰期履约节点存在延迟，客服解释成本上升。", "梳理接单、备货、出库和签收时点，明确异常升级规则。"],
    ["门店协同", "部分门店反馈总部活动节奏偏紧，物料到位时间不一致。", "建立活动预告日历，提前校准库存、培训和陈列要求。"],
    ["客服体验", "重复咨询集中在费用、进度和售后边界，知识库需要更新。", "补齐高频问答、工单标签和回访机制，缩短首响时间。"],
    ["供应稳定", "关键物料存在区域性缺口，替代方案审批链条较长。", "分级管理供应商风险，建立备选清单和临时调拨流程。"],
    ["内容运营", "短内容曝光增加但收藏和咨询承接不足。", "按主题拆分选题、落地页和跟进话术，追踪阅读后的动作转化。"],
    ["社群转化", "社群活跃靠少数管理员推动，新用户进入后缺少分层引导。", "设置入群七日任务、主题答疑和重点用户跟进节奏。"],
    ["数据治理", "指标口径在销售、运营和财务之间存在差异。", "统一核心字段定义，沉淀指标说明和取数责任人。"],
    ["费用控制", "部分活动成本归集滞后，复盘时难以及时判断投入产出。", "提前绑定预算科目和审批节点，按周核对执行消耗。"],
    ["产品反馈", "用户建议分散在客服、社群和门店记录中，优先级判断不统一。", "建立反馈池，按频次、影响面和实现成本形成排序。"],
    ["培训支持", "一线人员对新政策理解不均衡，执行解释口径有偏差。", "采用短课、演练和抽查组合，确保关键话术可复述。"],
    ["活动复盘", "活动结束后只汇总结果数据，缺少过程节点分析。", "把预热、爆发、收尾拆成独立阶段，分别记录问题和改进。"],
    ["风险预警", "异常指标发现依赖人工查看，预警时效不足。", "设置阈值、通知对象和处置时限，形成闭环记录。"],
    ["跨区支持", "区域之间经验沉淀不足，优秀做法复制速度慢。", "提炼样板案例，安排区域互评和复用清单。"],
    ["用户分层", "同一套触达策略覆盖全部用户，信息匹配度不高。", "按价值、偏好和生命周期设计不同内容与服务动作。"],
    ["渠道库存", "渠道库存周转差异大，部分品类出现结构性积压。", "按品类、区域和渠道建立预警，及时调整补货计划。"],
    ["售后闭环", "售后问题处理完成后缺少二次确认，满意度回收不足。", "增加结果确认、原因归档和复发预防动作。"],
    ["线索培育", "潜在线索进入后缺少持续教育内容，转化周期不可控。", "设计分阶段培育内容，记录每次互动后的下一步动作。"],
    ["品牌口碑", "外部评价中服务细节被频繁提及，正向案例传播不足。", "沉淀典型服务案例，补充负面反馈响应模板。"],
    ["系统效率", "人工导出和手工整理占用运营时间，数据更新频次不足。", "梳理可自动化报表，减少重复搬运和口径误差。"],
    ["项目排期", "多个重点项目并行，关键依赖关系不够透明。", "建立里程碑视图，标注依赖、风险和决策节点。"],
    ["质量巡检", "巡检记录存在描述不统一问题，整改结果难比较。", "规范巡检字段，要求问题、责任、证据和完成时间同步记录。"],
    ["复购激励", "激励策略对不同客群的触发效果差异明显。", "分客群测试权益组合，比较转化、成本和长期留存表现。"]
  ];
  const sections = Array.from({ length: 24 }, (_, index) => {
    const chapter = index + 1;
    const [topic, current, action] = topics[index];
    const evidence = ["经营看板", "客服工单", "门店记录", "财务台账", "用户访谈", "活动复盘"][index % 6];
    const decision = ["资源倾斜", "节奏调整", "流程优化", "培训补强", "风险预警", "标准沉淀"][index % 6];
    const reviewFocus = ["执行偏差", "成本变化", "协作阻塞", "用户反馈", "质量波动", "时效风险"][index % 6];
    const controlPoint = ["检查频次", "验收口径", "责任边界", "升级路径", "证据留存", "完成时限"][index % 6];
    return {
      heading: `第${chapter}部分 ${topic}`,
      level: 1,
      intro: `${topic}是年度运营复盘中的独立专题，本节依据${evidence}说明现状、影响和${decision}方向。`,
      blocks: [
        {
          type: "paragraph",
          text: `${current}${action}分析时同步关注${evidence}的完整性、${reviewFocus}和改进成本，便于形成可追踪的${decision}建议。`
        },
        {
          type: "table",
          headers: ["维度", "当前情况", "后续动作"],
          rows: [
            ["进展", current, action],
            ["风险", `${topic}若缺少持续记录，会影响复盘判断和责任追踪。`, `明确${topic}牵头人、${controlPoint}和截止时间。`]
          ]
        },
        {
          type: "numbered_list",
          items: [`核对${topic}基础数据。`, `确认${topic}责任分工。`, `输出${topic}复盘结论。`]
        }
      ]
    };
  });

  const markdown = `WORD_DOCUMENT_PLAN_JSON\n${JSON.stringify({
    title: "年度运营复盘长文档",
    subtitle: "长文档稳定性测试",
    documentType: "report",
    sections
  })}`;

  const buffer = createDocxBuffer({
    markdown,
    title: "年度运营复盘长文档",
    template: "report",
    prompt: "生成一份年度运营复盘长文档，要求包含二十个以上专题、表格和步骤清单。"
  });
  const docx = parseDocxPackage(buffer);
  const documentXml = docx.getText("word/document.xml") || "";
  const numberingXml = docx.getText("word/numbering.xml") || "";
  const text = textFromXml(documentXml);
  const footerXml = docx.getText("word/footer1.xml") || "";
  const sectionCount = (documentXml.match(/w:pStyle w:val="Heading1"/g) || []).length;
  const tableCount = (documentXml.match(/<w:tbl>/g) || []).length;
  const orderedNumDefinitions = [...numberingXml.matchAll(/<w:num w:numId="(\d+)">/g)]
    .map((match) => Number(match[1]))
    .filter((numId) => numId >= 2).length;

  assert(buffer.length > 90_000, `Expected a substantial long DOCX package, got ${buffer.length} bytes.`);
  assert(sectionCount >= 24, `Expected at least 24 Heading1 sections, got ${sectionCount}.`);
  assert(tableCount >= 24, `Expected at least 24 tables, got ${tableCount}.`);
  assert(text.includes("章节概览"), "Long document should include a section overview.");
  assert(documentXml.includes("<w:footerReference"), "Long document should include footer reference.");
  assert(footerXml.includes("PAGE"), "Long document footer should include page number field.");
  assert(orderedNumDefinitions >= 24, `Each numbered list should get an independent numId, got ${orderedNumDefinitions}.`);
  assert(!/DocTemplate|NexusAI|Generated by NexusAI/i.test(text), "Long document must not include internal markers or platform signature.");

  console.log(JSON.stringify({ ok: true, bytes: buffer.length, sectionCount, tableCount, orderedNumDefinitions }, null, 2));
}

try {
  main();
} catch (error) {
  console.error(error);
  process.exitCode = 1;
}
