import { evaluateDeckQuality } from "../lib/presentation/v2/qa";
import { repairDeckIfNeeded } from "../lib/presentation/v2/repair";

function assert(condition: unknown, label: string): asserts condition {
  if (!condition) throw new Error(label);
}

const deck = {
  title: "Animation Teaching Deck",
  style: "teaching",
  slides: [
    {
      type: "cover",
      layoutPreset: "teaching_cover",
      title: "Keyframe Animation",
      subtitle: "Classroom lesson"
    },
    {
      type: "cards",
      layoutPreset: "knowledge_cards",
      title: "Overview",
      bullets: ["Important points"]
    },
    {
      type: "timeline",
      layoutPreset: "process_steps",
      title: "Steps",
      bullets: []
    }
  ]
};

const beforeReport = evaluateDeckQuality(deck);
assert(beforeReport.shouldRepair, "Expected sparse deck to require repair");

async function main() {
  const repaired = await repairDeckIfNeeded(deck, beforeReport, { maxRepairPasses: 1, minSlideScore: 70 });

  assert(repaired.slides.length === deck.slides.length, "Repair should not change slide count");

  const repairedText = JSON.stringify(repaired);
  assert(!repairedText.includes("Generated by NexusAI"), "Repair should not add English platform signature");
  assert(!repairedText.includes("由 NexusAI 生成"), "Repair should not add Chinese platform signature");

  for (const index of beforeReport.lowQualitySlides) {
    const slide = repaired.slides[index];
    assert((slide.bullets || []).length >= 3 || (slide.metrics || []).length >= 2 || (slide.table || []).length >= 3, `Slide ${index} should gain content`);
    assert(String(slide.speakerNotes || "").trim().length >= 40, `Slide ${index} should gain useful speaker notes`);
    assert(String(slide.visualBrief || "").trim().length >= 20, `Slide ${index} should gain visual brief`);
    assert(String(slide.imageQuery || "").trim().length >= 12, `Slide ${index} should gain image query`);
  }

  const afterReport = evaluateDeckQuality(repaired);
  assert(afterReport.totalScore > beforeReport.totalScore, `Expected repair to improve score: before=${beforeReport.totalScore}, after=${afterReport.totalScore}`);

  console.log(
    JSON.stringify({ ok: true, before: beforeReport.totalScore, after: afterReport.totalScore, slides: repaired.slides.length }, null, 2)
  );
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
