import { createDocxBuffer } from "@/lib/document/create";
import { buildWordDocumentPlan } from "@/lib/document/plan";
import { evaluateWordDocumentPlan, repairWordDocumentPlan } from "@/lib/document/quality";
import { parseDocxPackage } from "@/lib/document/docx-package";

function assert(condition: unknown, label: string): asserts condition {
  if (!condition) throw new Error(label);
}

function main() {
  const markdown = `# 三维动画第一章教学设计

## 教学目标

1. 理解关键帧和补间动画的关系。
2. 能够分析运动曲线对动画节奏的影响。
3. 形成规范记录和复盘的学习习惯。

## 教学过程

1. 案例导入。
2. 教师示范。
3. 学生练习。
4. 展示评价。
`;

  const plan = buildWordDocumentPlan({ markdown, title: "三维动画第一章教案", template: "lesson_plan" });
  const report = evaluateWordDocumentPlan(plan);
  const repaired = report.shouldRepair ? repairWordDocumentPlan(plan) : plan;

  assert(repaired.documentType === "lesson_plan", "Expected lesson plan document type");
  for (const heading of ["课程基本信息", "教学目标", "教学过程", "教学评价"]) {
    assert(repaired.sections.some((section) => section.heading.includes(heading)), `Expected ${heading} section`);
  }
  assert(repaired.sections.every((section) => section.intro || section.blocks.some((block) => block.type === "paragraph" || block.type === "table")), "Every section should have narrative or table body");
  assert(repaired.sections.some((section) => section.blocks.some((block) => block.type === "table")), "Expected lesson plan tables");

  const buffer = createDocxBuffer({ markdown, title: "三维动画第一章教案", template: "lesson_plan" });
  const docx = parseDocxPackage(buffer);
  const documentXml = docx.getText("word/document.xml") || "";

  assert(documentXml.includes("课程基本信息"), "DOCX should include basic course information");
  assert(documentXml.includes("教学过程"), "DOCX should include teaching process");
  assert(documentXml.includes("<w:tbl>"), "DOCX should render tables");
  assert(!/Generated by NexusAI|由\s*NexusAI\s*生成|NexusAI\s*智能文档模块/i.test(documentXml), "DOCX should not include platform signature");

  const numberedParagraphCount = (documentXml.match(/<w:numId w:val="2"\/>/g) || []).length;
  assert(numberedParagraphCount <= 3, `Expected limited numbered paragraphs, got ${numberedParagraphCount}`);

  console.log(JSON.stringify({ ok: true, sections: repaired.sections.length, numberedParagraphCount, bytes: buffer.length }, null, 2));
}

try {
  main();
} catch (error) {
  console.error(error);
  process.exitCode = 1;
}
