import { existsSync, readFileSync } from "node:fs";
import { resolve } from "node:path";

import { runAgent } from "../lib/agent/router";
import { parseDocxPackage } from "../lib/document/docx-package";

function assert(condition: unknown, label: string): asserts condition {
  if (!condition) throw new Error(label);
}

function resolveMockStorageUrl(url: string) {
  assert(url.startsWith("/mock-storage/"), `Expected mock storage URL, got ${url}`);
  return resolve(process.cwd(), "public", url.replace(/^\//, ""));
}

async function main() {
  process.env.ALLOW_LOCAL_STORAGE_FALLBACK = "true";
  process.env.CLAUDECODER_API_KEY = "";
  process.env.MOONSHOT_API_KEY = "";
  process.env.AGENT_KIMI_API_KEY = "";
  process.env.ALI_OSS_BUCKET = "";
  process.env.ALI_OSS_ACCESS_KEY_ID = "";
  process.env.ALI_OSS_ACCESS_KEY_SECRET = "";
  process.env.ALI_OSS_ENDPOINT = "";

  const result = await runAgent({
    userId: "word-agent-quality-e2e",
    messages: [{ role: "user", content: "帮我生成一个三维动画第一章教学的教案 Word，内容要正式、可直接交付" }],
    files: [],
    signal: new AbortController().signal
  });

  assert(result.agentTask?.type === "create_document", `Expected create_document, got ${result.agentTask?.type}`);
  assert(result.generatedFiles[0]?.fileName.endsWith(".docx"), "Expected generated docx file");

  const outputPath = resolveMockStorageUrl(result.generatedFiles[0].url || "");
  assert(existsSync(outputPath), `Expected generated docx at ${outputPath}`);

  const packageBuffer = readFileSync(outputPath);
  const documentXml = parseDocxPackage(packageBuffer).getText("word/document.xml") || "";

  for (const expected of ["课程基本信息", "教学目标", "教学过程", "教学评价", "课后作业", "教学反思"]) {
    assert(documentXml.includes(expected), `Expected ${expected} in generated Word`);
  }
  assert(documentXml.includes("<w:tbl>"), "Expected generated Word to contain tables");
  assert(documentXml.includes("<w:ind w:firstLine="), "Expected generated Word to contain natural paragraphs with first-line indent");
  assert(!/Generated by NexusAI|由\s*NexusAI\s*生成|NexusAI\s*智能文档模块/i.test(documentXml), "Generated Word should not contain platform signature");

  const numberedParagraphCount = (documentXml.match(/<w:numId w:val="2"\/>/g) || []).length;
  assert(numberedParagraphCount <= 5, `Generated Word should not be a document-wide numbered outline, got ${numberedParagraphCount}`);

  console.log(JSON.stringify({ ok: true, fileName: result.generatedFiles[0].fileName, sizeBytes: packageBuffer.length, numberedParagraphCount }, null, 2));
}

main().catch((error) => {
  console.error(error);
  process.exitCode = 1;
});
